/**
 * Stable, machine-readable error codes for the API's typed error system.
 * Codes are part of the client-facing contract â€” renaming one is a breaking
 * change for any consumer that branches on `error.code`.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_INVALID = 'AUTHENTICATION_INVALID',
  AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED',
  // Wire value stays `CENTRAL_TOKEN_EXPIRED` for backward compatibility â€”
  // the Flutter client's AuthInterceptor and error mappers already key their
  // single-flight refresh-and-retry flow off this exact string.
  ACCESS_TOKEN_EXPIRED = 'CENTRAL_TOKEN_EXPIRED',
  TOKEN_AUDIENCE_INVALID = 'TOKEN_AUDIENCE_INVALID',
  MEDIA_UPLOAD_FORBIDDEN = 'MEDIA_UPLOAD_FORBIDDEN',
  MEDIA_TYPE_UNSUPPORTED = 'MEDIA_TYPE_UNSUPPORTED',
  MEDIA_SIZE_EXCEEDED = 'MEDIA_SIZE_EXCEEDED',
  MEDIA_NOT_OWNED = 'MEDIA_NOT_OWNED',
  MEDIA_BINDING_CONFLICT = 'MEDIA_BINDING_CONFLICT',
  UPLOAD_INCOMPLETE = 'UPLOAD_INCOMPLETE',
  INVALID_DRAFT_STATE = 'INVALID_DRAFT_STATE',
  RETRYABLE_UPLOAD_FAILURE = 'RETRYABLE_UPLOAD_FAILURE',
  RESOURCE_OWNERSHIP_REQUIRED = 'RESOURCE_OWNERSHIP_REQUIRED',
  FUNDRAISER_NOT_FOUND = 'FUNDRAISER_NOT_FOUND',
  FUNDRAISER_NOT_PUBLIC = 'FUNDRAISER_NOT_PUBLIC',
  FUNDRAISER_ACCESS_DENIED = 'FUNDRAISER_ACCESS_DENIED',
  FUNDRAISER_NOT_DONATABLE = 'FUNDRAISER_NOT_DONATABLE',
  FUNDRAISER_EDIT_FORBIDDEN = 'FUNDRAISER_EDIT_FORBIDDEN',
  /// Payout-sensitive operations only (withdrawal / cash-out / payout
  /// activation). Never raised by campaign create/save/submit or donation
  /// acceptance — see `fundraising-policy.ts`.
  FUNDRAISING_ACCOUNT_NOT_VERIFIED = 'FUNDRAISING_ACCOUNT_NOT_VERIFIED',
  /// Donation checkout could not obtain a real payment-provider redirect —
  /// never paired with a 200 success; the checkout attempt itself failed.
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  LOCATION_PARENT_INVALID = 'LOCATION_PARENT_INVALID',
  ANIMAL_TYPE_NOT_FOUND = 'ANIMAL_TYPE_NOT_FOUND',
  ANIMAL_BREED_NOT_FOUND = 'ANIMAL_BREED_NOT_FOUND',
  ANIMAL_BREED_SPECIES_MISMATCH = 'ANIMAL_BREED_SPECIES_MISMATCH',
  CONFLICT = 'CONFLICT',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED = 'RATE_LIMITED',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERIALIZATION_ERROR = 'SERIALIZATION_ERROR',
  ADOPTION_NOT_FOUND = 'ADOPTION_NOT_FOUND',
  ADOPTION_ACCESS_DENIED = 'ADOPTION_ACCESS_DENIED',
  ADOPTION_EDIT_FORBIDDEN = 'ADOPTION_EDIT_FORBIDDEN',
  ADOPTION_NOT_PUBLIC = 'ADOPTION_NOT_PUBLIC',
  ADOPTION_INVALID_STATUS = 'ADOPTION_INVALID_STATUS',
  ADOPTION_VALIDATION_FAILED = 'ADOPTION_VALIDATION_FAILED',
  ADOPTION_MEDIA_NOT_OWNED = 'ADOPTION_MEDIA_NOT_OWNED',
  ADOPTION_MEDIA_ALREADY_BOUND = 'ADOPTION_MEDIA_ALREADY_BOUND',
  ADOPTION_STATUS_TRANSITION_INVALID = 'ADOPTION_STATUS_TRANSITION_INVALID',
  ADOPTION_STATUS_CHANGE_FORBIDDEN = 'ADOPTION_STATUS_CHANGE_FORBIDDEN',
  ADOPTION_ALREADY_CLOSED = 'ADOPTION_ALREADY_CLOSED',
  ADOPTION_DATE_INVALID = 'ADOPTION_DATE_INVALID',
  ADOPTION_LOCATION_REQUIRED = 'ADOPTION_LOCATION_REQUIRED',
}
