/**
 * Stable, machine-readable error codes for the API's typed error system.
 * Codes are part of the client-facing contract — renaming one is a breaking
 * change for any consumer that branches on `error.code`.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_INVALID = 'AUTHENTICATION_INVALID',
  AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED',
  CONFLICT = 'CONFLICT',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED = 'RATE_LIMITED',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERIALIZATION_ERROR = 'SERIALIZATION_ERROR',
}
