-- Import BD Areas (Batch 10)
INSERT INTO bd_areas (code, "nameEn", "nameBn", type, "upazilaId", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('ARE-4501', 'Mendipur', 'মেন্দিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4502', 'Gazipur', 'গাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4503', 'Koilati', 'কৈলাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4504', 'Najirpur', 'নাজিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4505', 'Pogla', 'পোগলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4506', 'Kolmakanda', 'কলমাকান্দা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4507', 'Rongchati', 'রংছাতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4508', 'Lengura', 'লেংগুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4509', 'Borokhapon', 'বড়খাপন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4510', 'Kharnoi', 'খারনৈ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4511', 'Borokashia Birampur', 'বড়কাশিয়া বিরামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4512', 'Borotoli Banihari', 'বড়তলী বানিহারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4513', 'Tetulia', 'তেতুলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4514', 'Maghan Siadar', 'মাঘান সিয়াদার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4515', 'Somaj Sohildeo', 'সমাজ সহিলদেও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4516', 'Suair', 'সুয়াইর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4517', 'Gaglajur', 'গাগলাজুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4518', 'Khalishaur', 'খলিশাউড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4519', 'Ghagra', 'ঘাগড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4520', 'Jaria', 'জারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4521', 'Narandia', 'নারান্দিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4522', 'Bishkakuni', 'বিশকাকুনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4523', 'Bairaty', 'বৈরাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4524', 'Hogla', 'হোগলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4525', 'Gohalakanda', 'গোহালাকান্দা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4526', 'Dhalamulgaon', 'ধলামুলগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4527', 'Agia', 'আগিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4528', 'Purbadhala', 'পূর্বধলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4529', 'Chollisha', 'চল্লিশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4530', 'Kailati', 'কাইলাটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4531', 'Dokkhin Bishiura', 'দক্ষিণ বিশিউড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4532', 'Modonpur', 'মদনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4533', 'Amtola', 'আমতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4534', 'Lokkhiganj', 'লক্ষীগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4535', 'Singher Bangla', 'সিংহের বাংলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4536', 'Thakurakona', 'ঠাকুরাকোণা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4537', 'Mougati', 'মৌগাতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4538', 'Rouha', 'রৌহা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4539', 'Medni', 'মেদনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4540', 'Kaliara Babragati', 'কালিয়ারা গাবরাগাতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW());