-- Import BD Areas (Batch 6)
INSERT INTO bd_areas (code, "nameEn", "nameBn", type, "upazilaId", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('ARE-2501', 'Darbast', 'দরবস্ত', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2502', 'Fatehpur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2503', 'Chiknagul', 'চিকনাগুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2504', 'Rajagonj', 'রাজাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2505', 'Lakshiprashad Purbo', 'লক্ষীপ্রাসাদ পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2506', 'Lakshiprashad Pashim', 'লক্ষীপ্রাসাদ পশ্চিম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2507', 'Digirpar Purbo', 'দিঘিরপার পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2508', 'Satbakh', 'সাতবাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2509', 'Barachotul', 'বড়চতুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2510', 'Kanaighat', 'কানাইঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2511', 'Dakhin Banigram', 'দক্ষিন বানিগ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2512', 'Jinghabari', 'ঝিঙ্গাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2513', 'Jalalabad', 'জালালাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2514', 'Hatkhula', 'হাটখোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2515', 'Khadimnagar', 'খাদিমনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2516', 'Khadimpara', 'খাদিমপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2517', 'Tultikor', 'টুলটিকর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2518', 'Tukerbazar', 'টুকেরবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2519', 'Mugolgaon', 'মোগলগাও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2520', 'Kandigaon', 'কান্দিগাও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2521', 'Manikpur', 'মানিকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2522', 'Sultanpur', 'সুলতানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2523', 'Barohal', 'বারহাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2524', 'Birorsri', 'বিরশ্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2525', 'Kajalshah', 'কাজলশার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2526', 'Kolachora', 'কলাছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2527', 'Zakiganj', 'জকিগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2528', 'Barothakuri', 'বারঠাকুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2529', 'Kaskanakpur', 'কসকনকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2530', 'Lalabazar', 'লালাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2531', 'Moglabazar', 'মোগলাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2532', 'Boroikandi', 'বড়ইকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2533', 'Silam', 'সিলাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2534', 'Daudpur', 'দাউদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2535', 'Mollargaon', 'মোল্লারগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2536', 'Kuchai', 'কুচাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2537', 'Kamalbazar', 'কামালবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2538', 'Jalalpur', 'জালালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2539', 'Tetli', 'তেতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2540', 'Talimpur', 'তালিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2541', 'Borni', 'বর্ণি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2542', 'Dasherbazar', 'দাসেরবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2543', 'Nizbahadurpur', 'নিজবাহাদুরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2544', 'Uttar Shahbajpur', 'উত্তর শাহবাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2545', 'Dakkhin Shahbajpur', 'দক্ষিণ শাহবাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2546', 'Talimpur', 'তালিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2547', 'Baralekha', 'বড়লেখা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2548', 'Dakshinbhag Uttar', 'দক্ষিণভাগ (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2549', 'Dakshinbhag Dakkhin', 'দক্ষিণভাগ (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2550', 'Sujanagar', 'সুজানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2551', 'Adampur', 'আদমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2552', 'Patanushar', 'পতনঊষার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2553', 'Madhabpur', 'মাধবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2554', 'Rahimpur', 'রহিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2555', 'Shamshernagar', 'শমশেরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2556', 'Kamalgonj', 'কমলগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2557', 'Islampur', 'ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2558', 'Munshibazar', 'মুন্সিবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2559', 'Alinagar', 'আলী নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2560', 'Baramchal', 'বরমচাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2561', 'Bhukshimail', 'ভূকশিমইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2562', 'Joychandi', 'জয়চন্ডি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2563', 'Brammanbazar', 'ব্রাহ্মণবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2564', 'Kadipur', 'কাদিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2565', 'Kulaura', 'কুলাউড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2566', 'Rauthgaon', 'রাউৎগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2567', 'Tilagaon', 'টিলাগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2568', 'Sharifpur', 'শরীফপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2569', 'Prithimpassa', 'পৃথিমপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2570', 'Kormodha', 'কর্মধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2571', 'Bhatera', 'ভাটেরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2572', 'Hazipur', 'হাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2573', 'Amtail', 'আমতৈল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2574', 'Khalilpur', 'খলিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2575', 'Monumukh', 'মনুমুখ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2576', 'Kamalpur', 'কামালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2577', 'Apar Kagabala', 'আপার কাগাবলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2578', 'Akhailkura', 'আখাইলকুড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2579', 'Ekatuna', 'একাটুনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2580', 'Chadnighat', 'চাঁদনীঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2581', 'Konokpur', 'কনকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2582', 'Nazirabad', 'নাজিরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2583', 'Mostafapur', 'মোস্তফাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2584', 'Giasnagar', 'গিয়াসনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2585', 'Fotepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2586', 'Uttorbhag', 'উত্তরভাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2587', 'Munsibazar', 'মুন্সিবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2588', 'Panchgaon', 'পাঁচগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2589', 'Rajnagar', 'রাজনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2590', 'Tengra', 'টেংরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2591', 'Kamarchak', 'কামারচাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2592', 'Munsurnagar', 'মনসুরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2593', 'Mirzapur', 'মির্জাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2594', 'Bhunabir', 'ভূনবীর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2595', 'Sreemangal', 'শ্রীমঙ্গল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2596', 'Sindurkhan', 'সিন্দুরখান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2597', 'Kalapur', 'কালাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2598', 'Ashidron', 'আশিদ্রোন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2599', 'Rajghat', 'রাজঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2600', 'Kalighat', 'কালীঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2601', 'Satgaon', 'সাতগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2602', 'Jafornagar', 'জায়ফরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2603', 'West Juri', 'পশ্চিম জুড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2604', 'Gualbari', 'গোয়ালবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2605', 'Sagornal', 'সাগরনাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2606', 'Fultola', 'ফুলতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2607', 'Eastjuri', 'পুর্ব জুড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2608', 'Barabhakoir Paschim', 'বড় ভাকৈর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2609', 'Barabhakoir Purba', 'বড় ভাকৈর (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2610', 'Inatganj', 'ইনাতগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2611', 'Digholbak', 'দীঘলবাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2612', 'Aushkandi', 'আউশকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2613', 'Kurshi', 'কুর্শি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2614', 'Kargoan', 'করগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2615', 'Nabiganj Sadar', 'নবীগঞ্জ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2616', 'Bausha', 'বাউসা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2617', 'Debparra', 'দেবপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2618', 'Gaznaipur', 'গজনাইপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2619', 'Kaliarbhanga', 'কালিয়ারভাংগা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2620', 'Paniumda', 'পানিউমদা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2621', 'Snanghat', 'স্নানঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2622', 'Putijuri', 'পুটিজুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2623', 'Satkapon', 'সাতকাপন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2624', 'Bahubal Sadar', 'বাহুবল সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2625', 'Lamatashi', 'লামাতাশী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2626', 'Mirpur', 'মিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2627', 'Bhadeshwar', 'ভাদেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2628', 'Shibpasha', 'শিবপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2629', 'Kakailsao', 'কাকাইলছেও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2630', 'Ajmiriganj Sadar', 'আজমিরীগঞ্জ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2631', 'Badolpur', 'বদলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2632', 'Jolsuka', 'জলসুখা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2633', 'Baniachong North East', 'বানিয়াচং উত্তর পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2634', 'Baniachong North West', 'বানিয়াচং উত্তর পশ্চিম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2635', 'Baniachong South East', 'বানিয়াচং দক্ষিণ পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2636', 'Baniachong South West', 'বানিয়াচং দক্ষিণ পশ্চিম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2637', 'Daulatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2638', 'Khagaura', 'খাগাউড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2639', 'Baraiuri', 'বড়ইউড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2640', 'Kagapasha', 'কাগাপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2641', 'Pukra', 'পুকড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2642', 'Subidpur', 'সুবিদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2643', 'Makrampur', 'মক্রমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2644', 'Sujatpur', 'সুজাতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2645', 'Mandari', 'মন্দরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2646', 'Muradpur', 'মুরাদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2647', 'Pailarkandi', 'পৈলারকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2648', 'Lakhai', 'লাখাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2649', 'Murakari', 'মোড়াকরি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2650', 'Muriauk', 'মুড়িয়াউক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2651', 'Bamoi', 'বামৈ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2652', 'Karab', 'করাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2653', 'Bulla', 'বুল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2654', 'Gazipur', 'গাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2655', 'Ahammadabad', 'আহম্মদাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2656', 'Deorgach', 'দেওরগাছ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2657', 'Paikpara', 'পাইকপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2658', 'Shankhala', 'শানখলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2659', 'Chunarughat', 'চুনারুঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2660', 'Ubahata', 'উবাহাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2661', 'Shatiajuri', 'সাটিয়াজুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2662', 'Ranigaon', 'রাণীগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2663', 'Mirashi', 'মিরাশী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2664', 'Lukra', 'লুকড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2665', 'Richi', 'রিচি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2666', 'Teghoria', 'তেঘরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2667', 'Poil', 'পইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2668', 'Gopaya', 'গোপায়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2669', 'Rajiura', 'রাজিউড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2670', 'Nurpur', 'নুরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2671', 'Shayestaganj', 'শায়েস্তাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2672', 'Nijampur', 'নিজামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2673', 'Laskerpur', 'লস্করপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2674', 'Dharmaghar', 'ধর্মঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2675', 'Choumohani', 'চৌমুহনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2676', 'Bahara', 'বহরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2677', 'Adaoir', 'আদাঐর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2678', 'Andiura', 'আন্দিউড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2679', 'Shahjahanpur', 'শাহজাহানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2680', 'Jagadishpur', 'জগদীশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2681', 'Bulla', 'বুল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2682', 'Noapara', 'নোয়াপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2683', 'Chhatiain', 'ছাতিয়াইন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2684', 'Bagashura', 'বাঘাসুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2685', 'Jahangirnagar', 'জাহাঙ্গীরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2686', 'Rangarchar', 'রংগারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2687', 'Aptabnagar', 'আপ্তাবনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2688', 'Gourarang', 'গৌরারং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2689', 'Mollapara', 'মোল্লাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2690', 'Laxmansree', 'লক্ষণশ্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2691', 'Kathair', 'কাঠইর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2692', 'Surma', 'সুরমা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2693', 'Mohonpur', 'মোহনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2694', 'Shimulbak', 'শিমুলবাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2695', 'Paschim Pagla', 'পশ্চিম পাগলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2696', 'Joykalash', 'জয়কলস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2697', 'Purba Pagla', 'পূর্ব পাগলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2698', 'Patharia', 'পাথারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2699', 'Purba Birgaon', 'পূর্ব বীরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2700', 'Dargapasha', 'দরগাপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2701', 'Paschim Birgaon', 'পশ্চিম বীরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2702', 'Palash', 'পলাশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2703', 'Solukabad', 'সলুকাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2704', 'Dhanpur', 'ধনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2705', 'Badaghat South', 'বাদাঘাট দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2706', 'Fatepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2707', 'Islampur', 'ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2708', 'Noarai', 'নোয়ারাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2709', 'Chhatak Sadar', 'ছাতক সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2710', 'Kalaruka', 'কালারুকা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2711', 'Gobindganj-Syedergaon', 'গোবিন্দগঞ্জ-সৈদেরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2712', 'Chhaila Afjalabad', 'ছৈলা আফজলাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2713', 'Khurma North', 'খুরমা উত্তর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2714', 'Khurma South', 'খুরমা দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2715', 'Chormohalla', 'চরমহল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2716', 'Jauwabazar', 'জাউয়া বাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2717', 'Singchapair', 'সিংচাপইড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2718', 'Dolarbazar', 'দোলারবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2719', 'Bhatgaon', 'ভাতগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2720', 'Kolkolia', 'কলকলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2721', 'Patli', 'পাটলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2722', 'Mirpur', 'মীরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2723', 'Chilaura Holdipur', 'চিলাউড়া হলদিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2724', 'Raniganj', 'রানীগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2725', 'Syedpur Shaharpara', 'সৈয়দপুর শাহাড়পাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2726', 'Asharkandi', 'আশারকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2727', 'Pailgaon', 'পাইলগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2728', 'Banglabazar', 'বাংলাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2729', 'Norsingpur', 'নরসিংহপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2730', 'Dowarabazar', 'দোয়ারাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2731', 'Mannargaon', 'মান্নারগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2732', 'Pandargaon', 'পান্ডারগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2733', 'Dohalia', 'দোহালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2734', 'Laxmipur', 'লক্ষীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2735', 'Boglabazar', 'বোগলাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2736', 'Surma', 'সুরমা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2737', 'Sreepur North', 'শ্রীপুর উত্তর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2738', 'Sreepur South', 'শ্রীপুর দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2739', 'Bordal South', 'বড়দল দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2740', 'Bordal North', 'বড়দল উত্তর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2741', 'Badaghat', 'বাদাঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2742', 'Tahirpur Sadar', 'তাহিরপুর সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2743', 'Balijuri', 'বালিজুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2744', 'Bongshikunda North', 'বংশীকুন্ডা উত্তর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2745', 'Bongshikunda South', 'বংশীকুন্ডা দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2746', 'Chamordani', 'চামরদানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2747', 'Madhyanagar', 'মধ্যনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2748', 'Paikurati', 'পাইকুরাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2749', 'Selbarash', 'সেলবরষ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2750', 'Dharmapasha Sadar', 'ধর্মপাশা সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2751', 'Joyasree', 'জয়শ্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2752', 'Sukhair Rajapur North', 'সুখাইড় রাজাপুর উত্তর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2753', 'Sukhair Rajapur South', 'সুখাইড় রাজাপুর দক্ষিণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2754', 'Beheli', 'বেহেলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2755', 'Sachnabazar', 'সাচনাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2756', 'Bhimkhali', 'ভীমখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2757', 'Fenerbak', 'ফেনারবাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2758', 'Jamalganj Sadar', 'জামালগঞ্জ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2759', 'Atgaon', 'আটগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2760', 'Habibpur', 'হবিবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2761', 'Bahara', 'বাহারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2762', 'Shalla Sadar', 'শাল্লা সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2763', 'Rafinagar', 'রফিনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2764', 'Bhatipara', 'ভাটিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2765', 'Rajanagar', 'রাজানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2766', 'Charnarchar', 'চরনারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2767', 'Derai Sarmangal', 'দিরাই সরমঙ্গল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2768', 'Karimpur', 'করিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2769', 'Jagddol', 'জগদল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2770', 'Taral', 'তাড়ল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2771', 'Kulanj', 'কুলঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2772', 'Amlaba', 'আমলাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2773', 'Bajnaba', 'বাজনাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2774', 'Belabo', 'বেলাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2775', 'Binnabayd', 'বিন্নাবাইদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2776', 'Charuzilab', 'চরউজিলাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2777', 'Naraynpur', 'নারায়নপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2778', 'Sallabad', 'সল্লাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2779', 'Patuli', 'পাটুলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2780', 'Diara', 'দেয়ারা মডেল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2781', 'Barachapa', 'বড়চাপা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2782', 'Chalakchar', 'চালাকচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2783', 'Charmandalia', 'চরমান্দালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2784', 'Ekduaria', 'একদুয়ারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2785', 'Gotashia', 'গোতাশিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2786', 'Kanchikata', 'কাচিকাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2787', 'Khidirpur', 'খিদিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2788', 'Shukundi', 'শুকুন্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2789', 'Dawlatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2790', 'Krisnopur', 'কৃষ্ণপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2791', 'Labutala', 'লেবুতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2792', 'Chandanbari', 'চন্দনবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2793', 'Alokbali', 'আলোকবালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2794', 'Chardighaldi', 'চরদিঘলদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2795', 'Chinishpur', 'চিনিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2796', 'Hajipur', 'হাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2797', 'Karimpur', 'করিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2798', 'Khathalia', 'কাঠালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2799', 'Nuralapur', 'নূরালাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2800', 'Mahishasura', 'মহিষাশুড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2801', 'Meherpara', 'মেহেড়পাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2802', 'Nazarpur', 'নজরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2803', 'Paikarchar', 'পাইকারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2804', 'Panchdona', 'পাঁচদোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2805', 'Silmandi', 'শিলমান্দী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2806', 'Amdia', 'আমদিয়া ২', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2807', 'Danga', 'ডাংঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2808', 'Charsindur', 'চরসিন্দুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2809', 'Jinardi', 'জিনারদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2810', 'Gazaria', 'গজারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2811', 'Chanpur', 'চানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2812', 'Alipura', 'অলিপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2813', 'Amirganj', 'আমিরগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2814', 'Adiabad', 'আদিয়াবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2815', 'Banshgari', 'বাঁশগাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2816', 'Chanderkandi', 'চান্দেরকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2817', 'Chararalia', 'চরআড়ালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2818', 'Charmadhua', 'চরমধুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2819', 'Charsubuddi', 'চরসুবুদ্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2820', 'Daukarchar', 'ডৌকারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2821', 'Hairmara', 'হাইরমারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2822', 'Maheshpur', 'মহেষপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2823', 'Mirzanagar', 'মির্জানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2824', 'Mirzarchar', 'মির্জারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2825', 'Nilakhya', 'নিলক্ষ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2826', 'Palashtali', 'পলাশতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2827', 'Paratali', 'পাড়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2828', 'Sreenagar', 'শ্রীনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2829', 'Roypura', 'রায়পুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2830', 'Musapur', 'মুছাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2831', 'Uttar Bakharnagar', 'উত্তর বাখরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2832', 'Marjal', 'মরজাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2833', 'Dulalpur', 'দুলালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2834', 'Joynagar', 'জয়নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2835', 'Sadharchar', 'সাধারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2836', 'Masimpur', 'মাছিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2837', 'Chakradha', 'চক্রধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2838', 'Joshar', 'যোশর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2839', 'Baghabo', 'বাঘাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2840', 'Ayubpur', 'আয়ুবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2841', 'Putia', 'পুটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2842', 'Bahadursadi', 'বাহাদুরশাদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2843', 'Baktarpur', 'বক্তারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2844', 'Jamalpurnew', 'জামালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2845', 'Jangalia', 'জাঙ্গালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2846', 'Moktarpur', 'মোক্তারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2847', 'Nagari', 'নাগরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2848', 'Tumulia', 'তুমুলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2849', 'Atabaha', 'আটাবহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2850', 'Boali', 'বোয়ালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2851', 'Chapair', 'চাপাইর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2852', 'Dhaliora', 'ঢালজোড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2853', 'Fulbaria', 'ফুলবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2854', 'Madhyapara', 'মধ্যপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2855', 'Mouchak', 'মৌচাক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2856', 'Sutrapur', 'সূত্রাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2857', 'Srifaltali', 'শ্রীফলতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2858', 'Barishaba', 'বারিষাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2859', 'Ghagotia', 'ঘাগটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2860', 'Kapasia', 'কাপাসিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2861', 'Chandpur', 'চাঁদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2862', 'Targoan', 'তরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2863', 'Karihata', 'কড়িহাতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2864', 'Tokh', 'টোক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2865', 'Sinhasree', 'সিংহশ্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2866', 'Durgapur', 'দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2867', 'Sonmania', 'সনমানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2868', 'Rayed', 'রায়েদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2869', 'Baria', 'বাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2870', 'Basan', 'বাসন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2871', 'Gachha', 'গাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2872', 'Kashimpur', 'কাশিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2873', 'Kayaltia', 'কাউলতিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2874', 'Konabari', 'কোনাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2875', 'Mirzapur', 'মির্জাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2876', 'Pubail', 'পূবাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2877', 'Barmi', 'বরমী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2878', 'Gazipur', 'গাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2879', 'Gosinga', 'গোসিংগা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2880', 'Maona', 'মাওনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2881', 'Kaoraid', 'কাওরাইদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2882', 'Prahladpur', 'প্রহলাদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2883', 'Rajabari', 'রাজাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2884', 'Telihati', 'তেলিহাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2885', 'Binodpur', 'বিনোদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2886', 'Tulasar', 'তুলাসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2887', 'Palong', 'পালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2888', 'Domshar', 'ডোমসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2889', 'Rudrakar', 'রুদ্রকর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2890', 'Angaria', 'আংগারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2891', 'Chitolia', 'চিতলয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2892', 'Mahmudpur', 'মাহমুদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2893', 'Chikondi', 'চিকন্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2894', 'Chandrapur', 'চন্দ্রপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2895', 'Shulpara', 'শৌলপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2896', 'Kedarpur', 'কেদারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2897', 'Dingamanik', 'ডিংগামানিক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2898', 'Garishar', 'ঘড়িষার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2899', 'Nowpara', 'নওপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2900', 'Moktererchar', 'মোত্তারেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2901', 'Charatra', 'চরআত্রা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2902', 'Rajnagar', 'রাজনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2903', 'Japsa', 'জপসা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2904', 'Vojeshwar', 'ভোজেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2905', 'Fategongpur', 'ফতেজংপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2906', 'Bijari', 'বিঝারি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2907', 'Vumkhara', 'ভূমখাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2908', 'Nashason', 'নশাসন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2909', 'Zajira Sadar', 'জাজিরা সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2910', 'Mulna', 'মূলনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2911', 'Barokandi', 'বড়কান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2912', 'Bilaspur', 'বিলাসপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2913', 'Kundarchar', 'কুন্ডেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2914', 'Palerchar', 'পালেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2915', 'Purba Nawdoba', 'পুর্ব নাওডোবা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2916', 'Nawdoba', 'নাওডোবা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2917', 'Shenerchar', 'সেনেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2918', 'Bknagar', 'বি. কে. নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2919', 'Barogopalpur', 'বড়গোপালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2920', 'Jaynagor', 'জয়নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2921', 'Nager Para', 'নাগের পাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2922', 'Alaolpur', 'আলাওলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2923', 'Kodalpur', 'কোদালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2924', 'Goshairhat', 'গোসাইরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2925', 'Edilpur', 'ইদিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2926', 'Nalmuri', 'নলমুড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2927', 'Samontasar', 'সামন্তসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2928', 'Kuchipatti', 'কুচাইপট্টি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2929', 'Ramvadrapur', 'রামভদ্রপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2930', 'Mahisar', 'মহিষার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2931', 'Saygaon', 'ছয়গাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2932', 'Narayanpur', 'নারায়নপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2933', 'D.M Khali', 'ডি.এম খালি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2934', 'Charkumaria', 'চরকুমারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2935', 'Sakhipur', 'সখিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2936', 'Kachikata', 'কাচিকাঁটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2937', 'North Tarabunia', 'উত্তর তারাবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2938', 'Charvaga', 'চরভাগা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2939', 'Arsinagar', 'আরশিনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2940', 'South Tarabunia', 'দক্ষিন তারাবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2941', 'Charsensas', 'চরসেনসাস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2942', 'Shidulkura', 'শিধলকুড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2943', 'Kaneshar', 'কনেস্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2944', 'Purba Damudya', 'পুর্ব ডামুড্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2945', 'Islampur', 'ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2946', 'Dankati', 'ধানকাটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2947', 'Sidya', 'সিড্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2948', 'Darulaman', 'দারুল আমান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2949', 'Satgram', 'সাতগ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2950', 'Duptara', 'দুপ্তারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2951', 'Brahammandi', 'ব্রা‏হ্মন্দী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2952', 'Fatepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2953', 'Bishnandi', 'বিশনন্দী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2954', 'Mahmudpur', 'মাহমুদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2955', 'Highjadi', 'হাইজাদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2956', 'Uchitpura', 'উচিৎপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2957', 'Kalapaharia', 'কালাপাহাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2958', 'Kagkanda', 'খাগকান্দা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2959', 'Musapur', 'মুছাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2960', 'Modonpur', 'মদনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2961', 'Bandar', 'বন্দর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2962', 'Dhamgar', 'ধামগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2963', 'Kolagathia', ' কলাগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2964', 'Alirtek', 'আলিরটেক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2965', 'Kashipur', 'কাশীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2966', 'Kutubpur', 'কুতুবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2967', 'Gognagar', 'গোগনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2968', 'Baktaboli', 'বক্তাবলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2969', 'Enayetnagor', 'এনায়েত নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2970', 'Murapara', 'মুড়াপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2971', 'Bhulta', 'ভূলতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2972', 'Golakandail', 'গোলাকান্দাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2973', 'Daudpur', 'দাউদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2974', 'Rupganj', 'রূপগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2975', 'Kayetpara', 'কায়েতপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2976', 'Bholobo', 'ভোলাব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2977', 'Pirojpur', 'পিরোজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2978', 'Shambhupura', 'শম্ভুপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2979', 'Mograpara', 'মোগরাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2980', 'Baidyerbazar', 'বৈদ্যেরবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2981', 'Baradi', 'বারদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2982', 'Noagaon', 'নোয়াগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2983', 'Jampur', 'জামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2984', 'Sadipur', 'সাদীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2985', 'Sonmandi', 'সনমান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2986', 'Kanchpur', 'কাচপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2987', 'Basail', 'বাসাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2988', 'Kanchanpur', 'কাঞ্চনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2989', 'Habla', 'হাবলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2990', 'Kashil', 'কাশিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2991', 'Fulki', 'ফুলকি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2992', 'Kauljani', 'কাউলজানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2993', 'Arjuna', 'অর্জুনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2994', 'Gabshara', 'গাবসারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2995', 'Falda', 'ফলদা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2996', 'Gobindashi', 'গোবিন্দাসী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2997', 'Aloa', 'আলোয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2998', 'Nikrail', 'নিকরাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2999', 'Deuli', 'দেউলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-3000', 'Lauhati', 'লাউহাটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW());