-- Import BD Areas (Batch 5)
INSERT INTO bd_areas (code, "nameEn", "nameBn", type, "upazilaId", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('ARE-2001', 'Dhopakhali', 'ধোপাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2002', 'Moghia', 'মঘিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2003', 'Kachua', 'কচুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2004', 'Gopalpur', 'গোপালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2005', 'Raripara', 'রাড়ীপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2006', 'Badhal', 'বাধাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2007', 'Burrirdangga', 'বুড়িরডাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2008', 'Mithakhali', 'মিঠাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2009', 'Sonailtala', 'সোনাইলতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2010', 'Chadpai', 'চাঁদপাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2011', 'Chila', 'চিলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2012', 'Sundarban', 'সুন্দরবন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2013', 'Barobaria', 'বড়বাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2014', 'Kalatala', 'কলাতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2015', 'Hizla', 'হিজলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2016', 'Shibpur', 'শিবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2017', 'Chitalmari', 'চিতলমারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2018', 'Charbaniri', 'চরবানিয়ারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2019', 'Shantoshpur', 'সন্তোষপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2020', 'Sadhuhati', 'সাধুহাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2021', 'Modhuhati', 'মধুহাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2022', 'Saganna', 'সাগান্না', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2023', 'Halidhani', 'হলিধানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2024', 'Kumrabaria', 'কুমড়াবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2025', 'Ganna', 'গান্না', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2026', 'Maharazpur', 'মহারাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2027', 'Paglakanai', 'পাগলাকানাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2028', 'Porahati', 'পোড়াহাটী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2029', 'Harishongkorpur', 'হরিশংকরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2030', 'Padmakar', 'পদ্মাকর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2031', 'Dogachhi', 'দোগাছি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2032', 'Furshondi', 'ফুরসন্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2033', 'Ghorshal', 'ঘোড়শাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2034', 'Kalicharanpur', 'কালীচরণপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2035', 'Surat', 'সুরাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2036', 'Naldanga', 'নলডাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2037', 'Tribeni', 'ত্রিবেনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2038', 'Mirzapur', 'মির্জাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2039', 'Dignagore', 'দিগনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2040', 'Kancherkol', 'কাঁচেরকোল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2041', 'Sarutia', 'সারুটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2042', 'Hakimpur', 'হাকিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2043', 'Dhaloharachandra', 'ধলহরাচন্দ্র', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2044', 'Manoharpur', 'মনোহরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2045', 'Bogura', 'বগুড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2046', 'Abaipur', 'আবাইপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2047', 'Nityanandapur', 'নিত্যানন্দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2048', 'Umedpur', 'উমেদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2049', 'Dudshar', 'দুধসর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2050', 'Fulhari', 'ফুলহরি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2051', 'Bhayna', 'ভায়না', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2052', 'Joradah', 'জোড়াদহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2053', 'Taherhuda', 'তাহেরহুদা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2054', 'Daulatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2055', 'Kapashatia', 'কাপাশহাটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2056', 'Falsi', 'ফলসী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2057', 'Raghunathpur', 'রঘুনাথপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2058', 'Chandpur', 'চাঁদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2059', 'Sundarpurdurgapur', 'সুন্দরপুর-দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2060', 'Jamal', 'জামাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2061', 'Kola', 'কোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2062', 'Niamatpur', 'নিয়ামতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2063', 'Simla-Rokonpur', 'শিমলা-রোকনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2064', 'Trilochanpur', 'ত্রিলোচনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2065', 'Raygram', 'রায়গ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2066', 'Maliat', 'মালিয়াট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2067', 'Barabazar', 'বারবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2068', 'Kashtabhanga', 'কাষ্টভাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2069', 'Rakhalgachhi', 'রাখালগাছি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2070', 'Sabdalpur', 'সাবদালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2071', 'Dora', 'দোড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2072', 'Kushna', 'কুশনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2073', 'Baluhar', 'বলুহর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2074', 'Elangi', 'এলাঙ্গী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2075', 'Sbk', 'এস, বি, কে', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2076', 'Fatepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2077', 'Panthapara', 'পান্থপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2078', 'Swaruppur', 'স্বরুপপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2079', 'Shyamkur', 'শ্যামকুড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2080', 'Nepa', 'নেপা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2081', 'Kazirber', 'কাজীরবেড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2082', 'Banshbaria', 'বাঁশবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2083', 'Jadabpur', 'যাদবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2084', 'Natima', 'নাটিমা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2085', 'Manderbaria', 'মান্দারবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2086', 'Azampur', 'আজমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2087', 'Basanda', 'বাসন্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2088', 'Binoykati', 'বিনয়কাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2089', 'Gabharamchandrapur', 'গাভারামচন্দ্রপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2090', 'Keora', 'কেওড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2091', 'Kirtipasha', 'কীর্তিপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2092', 'Nabagram', 'নবগ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2093', 'Nathullabad', 'নথুলল্লাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2094', 'Ponabalia', 'পোনাবালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2095', 'Sekherhat', 'শেখেরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2096', 'Gabkhandhansiri', 'গাবখান ধানসিঁড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2097', 'Amua', 'আমুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2098', 'Awrabunia', 'আওরাবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2099', 'Chenchrirampur', 'চেঁচরীরামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2100', 'Kanthalia', 'কাঠালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2101', 'Patikhalghata', 'পাটিখালঘাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2102', 'Shaulajalia', 'শৌলজালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2103', 'Subidpur', 'সুবিদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2104', 'Siddhakati', 'সিদ্ধকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2105', 'Ranapasha', 'রানাপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2106', 'Nachanmohal', 'নাচনমহল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2107', 'Mollahat', 'মোল্লারহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2108', 'Magar', 'মগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2109', 'Kusanghal', 'কুশঙ্গল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2110', 'Kulkathi', 'কুলকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2111', 'Dapdapia', 'দপদপিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2112', 'Bharabpasha', 'ভৈরবপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2113', 'Suktagarh', 'শুক্তাগড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2114', 'Saturia', 'সাতুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2115', 'Mathbari', 'মঠবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2116', 'Galua', 'গালুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2117', 'Baraia', 'বড়ইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2118', 'Rajapur', 'রাজাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2119', 'Adabaria', 'আদাবারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2120', 'Bauphal', 'বাউফল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2121', 'Daspara', 'দাস পাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2122', 'Kalaiya', 'কালাইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2123', 'Nawmala', 'নওমালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2124', 'Najirpur', 'নাজিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2125', 'Madanpura', 'মদনপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2126', 'Boga', 'বগা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2127', 'Kanakdia', 'কনকদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2128', 'Shurjamoni', 'সূর্য্যমনি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2129', 'Keshabpur', 'কেশবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2130', 'Dhulia', 'ধুলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2131', 'Kalisuri', 'কালিশুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2132', 'Kachipara', 'কাছিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2133', 'Laukathi', 'লাউকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2134', 'Lohalia', 'লোহালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2135', 'Kamalapur', 'কমলাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2136', 'Jainkathi', 'জৈনকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2137', 'Kalikapur', 'কালিকাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2138', 'Badarpur', 'বদরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2139', 'Itbaria', 'ইটবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2140', 'Marichbunia', 'মরিচবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2141', 'Auliapur', 'আউলিয়াপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2142', 'Chotobighai', 'ছোট বিঘাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2143', 'Borobighai', 'বড় বিঘাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2144', 'Madarbunia', 'মাদারবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2145', 'Pangasia', 'পাংগাশিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2146', 'Muradia', 'মুরাদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2147', 'Labukhali', 'লেবুখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2148', 'Angaria', 'আংগারিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2149', 'Sreerampur', 'শ্রীরামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2150', 'Bashbaria', 'বাঁশবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2151', 'Rangopaldi', 'রণগোপালদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2152', 'Alipur', 'আলীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2153', 'Betagi Shankipur', 'বেতাগী সানকিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2154', 'Dashmina', 'দশমিনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2155', 'Baharampur', 'বহরমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2156', 'Chakamaia', 'চাকামইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2157', 'Tiakhali', 'টিয়াখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2158', 'Lalua', 'লালুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2159', 'Dhankhali', 'ধানখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2160', 'Mithagonj', 'মিঠাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2161', 'Nilgonj', 'নীলগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2162', 'Dulaser', 'ধুলাসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2163', 'Latachapli', 'লতাচাপলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2164', 'Mahipur', 'মহিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2165', 'Dalbugonj', 'ডালবুগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2166', 'Baliatali', 'বালিয়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2167', 'Champapur', 'চম্পাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2168', 'Madhabkhali', 'মাধবখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2169', 'Mirzaganj', 'মির্জাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2170', 'Amragachia', 'আমড়াগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2171', 'Deuli Subidkhali', 'দেউলী সুবিদখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2172', 'Kakrabunia', 'কাকড়াবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2173', 'Majidbaria', 'মজিদবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2174', 'Amkhola', 'আমখোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2175', 'Golkhali', 'গোলখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2176', 'Galachipa', 'গলাচিপা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2177', 'Panpatty', 'পানপট্টি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2178', 'Ratandi Taltali', 'রতনদী তালতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2179', 'Dakua', 'ডাকুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2180', 'Chiknikandi', 'চিকনিকান্দী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2181', 'Gazalia', 'গজালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2182', 'Charkajol', 'চরকাজল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2183', 'Charbiswas', 'চরবিশ্বাস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2184', 'Bakulbaria', 'বকুলবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2185', 'Kalagachhia', 'কলাগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2186', 'Rangabali', 'রাঙ্গাবালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2187', 'Barobaisdia', 'বড়বাইশদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2188', 'Chattobaisdia', 'ছোটবাইশদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2189', 'Charmontaz', 'চরমোন্তাজ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2190', 'Chalitabunia', 'চালিতাবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2191', 'Shikder Mallik', 'শিকদার মল্লিক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2192', 'Kodomtala', 'কদমতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2193', 'Durgapur', 'দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2194', 'Kolakhali', 'কলাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2195', 'Tona', 'টোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2196', 'Shariktola', 'শরিকতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2197', 'Shankorpasa', 'শংকরপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2198', 'Mativangga', 'মাটিভাংগা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2199', 'Malikhali', 'মালিখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2200', 'Daulbari Dobra', 'দেউলবাড়ী দোবড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2201', 'Dirgha', 'দীর্ঘা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2202', 'Kolardoania', 'কলারদোয়ানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2203', 'Sriramkathi', 'শ্রীরামকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2204', 'Shakhmatia', 'সেখমাটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2205', 'Nazirpur Sadar', 'নাজিরপুর সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2206', 'Shakharikathi', 'শাখারীকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2207', 'Sayna Rogunathpur', 'সয়না রঘুনাথপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2208', 'Amrazuri', 'আমড়াজুড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2209', 'Kawkhali Sadar', 'কাউখালি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2210', 'Chirapara', 'চিরাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2211', 'Shialkhathi', 'শিয়ালকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2212', 'Balipara', 'বালিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2213', 'Pattashi', 'পত্তাশি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2214', 'Parerhat', 'পাড়েরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2215', 'Vitabaria', 'ভিটাবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2216', 'Nodmulla', 'নদমূলা শিয়ালকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2217', 'Telikhali', 'তেলিখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2218', 'Ekree', 'ইকড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2219', 'Dhaoa', 'ধাওয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2220', 'Vandaria Sadar', 'ভান্ডারিয়া সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2221', 'Gouripur', 'গৌরীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2222', 'Tuskhali', 'তুষখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2223', 'Dhanisafa', 'ধানীসাফা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2224', 'Mirukhali', 'মিরুখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2225', 'Tikikata', 'টিকিকাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2226', 'Betmor Rajpara', 'বেতমোর রাজপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2227', 'Amragachia', 'আমড়াগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2228', 'Shapleza', 'শাপলেজা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2229', 'Daudkhali', 'দাউদখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2230', 'Mathbaria', 'মঠবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2231', 'Baramasua', 'বড়মাছুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2232', 'Haltagulishakhali', 'হলতাগুলিশাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2233', 'Boldia', 'বলদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2234', 'Sohagdal', 'সোহাগদল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2235', 'Atghorkuriana', 'আটঘর কুড়িয়ানা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2236', 'Jolabari', 'জলাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2237', 'Doyhary', 'দৈহারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2238', 'Guarekha', 'গুয়ারেখা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2239', 'Somudoykathi', 'সমুদয়কাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2240', 'Sutiakathi', 'সুটিয়াকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2241', 'Sarengkathi', 'সারেংকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2242', 'Shorupkathi', 'স্বরুপকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2243', 'Raipasha Karapur', 'রায়পাশা কড়াপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2244', 'Kashipur', 'কাশীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2245', 'Charbaria', 'চরবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2246', 'Shyastabad', 'সায়েস্তাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2247', 'Charmonai', 'চরমোনাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2248', 'Zagua', 'জাগুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2249', 'Charcowa', 'চরকাউয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2250', 'Chandpura', 'চাঁদপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2251', 'Tungibaria', 'টুঙ্গীবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2252', 'Chandramohan', 'চন্দ্রমোহন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2253', 'Charamaddi', 'চরামদ্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2254', 'Charade', 'চরাদি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2255', 'Darial', 'দাড়িয়াল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2256', 'Dudhal', 'দুধল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2257', 'Durgapasha', 'দুর্গাপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2258', 'Faridpur', 'ফরিদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2259', 'Kabai', 'কবাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2260', 'Nalua', 'নলুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2261', 'Kalashkathi', 'কলসকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2262', 'Garuria', 'গারুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2263', 'Bharpasha', 'ভরপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2264', 'Rangasree', 'রঙ্গশ্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2265', 'Padreeshibpur', 'পাদ্রিশিবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2266', 'Niamoti', 'নিয়ামতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2267', 'Jahangir Nagar', 'জাহাঙ্গীর নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2268', 'Kaderpur', 'কেদারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2269', 'Deherhoti', 'দেহেরগতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2270', 'Chandpasha', 'চাঁদপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2271', 'Rahamtpur', 'রহমতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2272', 'Madhbpasha', 'মাধবপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2273', 'Shatla', 'সাতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2274', 'Harta', 'হারতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2275', 'Jalla', 'জল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2276', 'Otra', 'ওটরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2277', 'Sholok', 'শোলক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2278', 'Barakhota', 'বরাকোঠা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2279', 'Bamrail', 'বামরাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2280', 'Shikerpur Wazirpur', 'শিকারপুর উজিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2281', 'Gouthia', 'গুঠিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2282', 'Bisharkandi', 'বিশারকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2283', 'Illuhar', 'ইলুহার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2284', 'Sayedkathi', 'সৈয়দকাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2285', 'Chakhar', 'চাখার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2286', 'Saliabakpur', 'সলিয়াবাকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2287', 'Baishari', 'বাইশারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2288', 'Banaripara', 'বানারিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2289', 'Udykhati', 'উদয়কাঠী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2290', 'Khanjapur', 'খাঞ্জাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2291', 'Barthi', 'বার্থী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2292', 'Chandshi', 'চাঁদশী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2293', 'Mahilara', 'মাহিলারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2294', 'Nalchira', 'নলচিড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2295', 'Batajore', 'বাটাজোর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2296', 'Sarikal', 'সরিকল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2297', 'Rajihar', 'রাজিহার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2298', 'Bakal', 'বাকাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2299', 'Bagdha', 'বাগধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2300', 'Goila', 'গৈলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2301', 'Ratnapur', 'রত্নপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2302', 'Andarmanik', 'আন্দারমানিক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2303', 'Lata', 'লতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2304', 'Charakkorea', 'চরএককরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2305', 'Ulania', 'উলানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2306', 'Mehendigong', 'মেহেন্দিগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2307', 'Biddanandapur', 'বিদ্যানন্দনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2308', 'Bhashanchar', 'ভাষানচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2309', 'Jangalia', 'জাঙ্গালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2310', 'Alimabad', 'আলিমাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2311', 'Chandpur', 'চানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2312', 'Darirchar Khajuria', 'দড়িরচর খাজুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2313', 'Gobindapur', 'গোবিন্দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2314', 'Chargopalpur', 'চরগোপালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2315', 'Batamara', 'বাটামারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2316', 'Nazirpur', 'নাজিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2317', 'Safipur', 'সফিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2318', 'Gaschua', 'গাছুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2319', 'Charkalekha', 'চরকালেখা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2320', 'Muladi', 'মুলাদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2321', 'Kazirchar', 'কাজিরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2322', 'Harinathpur', 'হরিনাথপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2323', 'Memania', 'মেমানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2324', 'Guabaria', 'গুয়াবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2325', 'Barjalia', 'বড়জালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2326', 'Hizla Gourabdi', 'হিজলা গৌরাব্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2327', 'Dhulkhola', 'ধুলখোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2328', 'Razapur', 'রাজাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2329', 'Ilisha', 'ইলিশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2330', 'Westilisa', 'পশ্চিম ইলিশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2331', 'Kachia', 'কাচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2332', 'Bapta', 'বাপ্তা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2333', 'Dhania', 'ধনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2334', 'Shibpur', 'শিবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2335', 'Alinagor', 'আলীনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2336', 'Charshamya', 'চরসামাইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2337', 'Vhelumia', ' ভেলুমিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2338', 'Vheduria', 'ভেদুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2339', 'North Digholdi', 'উত্তর দিঘলদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2340', 'South Digholdi', 'দক্ষিণ দিঘলদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2341', 'Boromanika', 'বড় মানিকা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2342', 'Deula', 'দেউলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2343', 'Kutuba', 'কুতুবা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2344', 'Pakshia', 'পক্ষিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2345', 'Kachia', 'কাচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2346', 'Osmangonj', 'ওসমানগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2347', 'Aslampur', 'আছলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2348', 'Zinnagor', 'জিন্নাগড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2349', 'Aminabad', 'আমিনাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2350', 'Nilkomol', 'নীলকমল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2351', 'Charmadraj', 'চরমাদ্রাজ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2352', 'Awajpur', 'আওয়াজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2353', 'Awajpur', 'আওয়াজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2354', 'Charkolmi', 'চরকলমী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2355', 'Charmanika', 'চরমানিকা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2356', 'Hazarigonj', 'হাজারীগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2357', 'Jahanpur', 'জাহানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2358', 'Nurabad', 'নুরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2359', 'Rasulpur', 'রসুলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2360', 'Kukrimukri', 'কুকরীমূকরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2361', 'Abubakarpur', 'আবুবকরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2362', 'Abdullahpur', 'আবদুল্লাহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2363', 'Nazrulnagar', 'নজরুল নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2364', 'Mujibnagar', 'মুজিব নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2365', 'Dalchar', 'ঢালচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2366', 'Madanpur', 'মদনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2367', 'Madua', 'মেদুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2368', 'Charpata', 'চরপাতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2369', 'North Joy Nagar', 'উত্তর জয়নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2370', 'South Joy Nagar', 'দক্ষিন জয়নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2371', 'Char Khalipa', 'চর খলিফা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2372', 'Sayedpur', 'সৈয়দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2373', 'Hazipur', 'হাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2374', 'Vhovanipur', 'ভবানীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2375', 'Hazirhat', 'হাজীর হাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2376', 'Monpura', 'মনপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2377', 'North Sakuchia', 'উত্তর সাকুচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2378', 'South Sakuchia', 'দক্ষিন সাকুচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2379', 'Chanchra', 'চাচঁড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2380', 'Shambupur', 'শম্ভুপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2381', 'Sonapur', 'সোনাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2382', 'Chadpur', 'চাঁদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2383', 'Baro Molongchora', 'বড় মলংচড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2384', 'Badarpur', 'বদরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2385', 'Charbhuta', 'চরভূতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2386', 'Kalma', ' কালমা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2387', 'Dholigour Nagar', 'ধলীগৌর নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2388', 'Lalmohan', 'লালমোহন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2389', 'Lord Hardinge', 'লর্ড হার্ডিঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2390', 'Ramagonj', 'রমাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2391', 'Paschim Char Umed', 'পশ্চিম চর উমেদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2392', 'Farajgonj', 'ফরাজগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2393', 'Amtali', 'আমতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2394', 'Gulishakhali', 'গুলিশাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2395', 'Athrogasia', 'আঠারগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2396', 'Kukua', 'কুকুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2397', 'Haldia', 'হলদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2398', 'Chotobogi', 'ছোটবগী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2399', 'Arpangasia', 'আড়পাঙ্গাশিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2400', 'Chowra', 'চাওড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2401', 'M. Baliatali', 'এম. বালিয়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2402', 'Noltona', 'নলটোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2403', 'Bodorkhali', 'বদরখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2404', 'Gowrichanna', 'গৌরিচন্না', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2405', 'Fuljhuri', 'ফুলঝুড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2406', 'Keorabunia', 'কেওড়াবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2407', 'Ayla Patakata', 'আয়লা পাতাকাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2408', 'Burirchor', 'বুড়িরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2409', 'Dhalua', 'ঢলুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2410', 'Barguna', 'বরগুনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2411', 'Bibichini', 'বিবিচিন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2412', 'Betagi', 'বেতাগী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2413', 'Hosnabad', 'হোসনাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2414', 'Mokamia', 'মোকামিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2415', 'Buramajumder', 'বুড়ামজুমদার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2416', 'Kazirabad', 'কাজীরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2417', 'Sarisamuri', 'সরিষামুড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2418', 'Bukabunia', 'বুকাবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2419', 'Bamna', 'বামনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2420', 'Ramna', 'রামনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2421', 'Doutola', 'ডৌয়াতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2422', 'Raihanpur', 'রায়হানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2423', 'Nachnapara', 'নাচনাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2424', 'Charduany', 'চরদুয়ানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2425', 'Patharghata', 'পাথরঘাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2426', 'Kalmegha', 'কালমেঘা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2427', 'Kakchira', 'কাকচিঢ়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2428', 'Kathaltali', 'কাঠালতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2429', 'Karibaria', 'কড়ইবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2430', 'Panchakoralia', 'পচাকোড়ালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2431', 'Barabagi', 'বড়বগি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2432', 'Chhotabagi', 'ছোটবগি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2433', 'Nishanbaria', 'নিশানবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2434', 'Sarikkhali', 'শারিকখালি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2435', 'Sonakata', 'সোনাকাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2436', 'Tazpur', 'তাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2437', 'Umorpur', 'উমরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2438', 'West Poilanpur', 'পশ্চিম পৈলনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2439', 'East Poilanpur', 'পূর্ব পৈলনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2440', 'Boaljur', 'বোয়ালজুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2441', 'Burungabazar', 'বুরুঙ্গাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2442', 'Goalabazar', 'গোয়ালাবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2443', 'Doyamir', 'দয়ামীর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2444', 'Usmanpur', 'উসমানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2445', 'Dewanbazar', 'দেওয়ান বাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2446', 'West Gouripur', 'পশ্চিম গৌরীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2447', 'East Gouripur', 'পূর্ব গৌরীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2448', 'Balaganj', 'বালাগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2449', 'Sadipur', 'সাদিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2450', 'Tilpara', 'তিলপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2451', 'Alinagar', 'আলীনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2452', 'Charkhai', 'চরখাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2453', 'Dubag', 'দুবাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2454', 'Sheola', 'শেওলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2455', 'Kurarbazar', 'কুড়ারবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2456', 'Mathiura', 'মাথিউরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2457', 'Mullapur', 'মোল্লাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2458', 'Muria', 'মুড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2459', 'Lauta', 'লাউতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2460', 'Rampasha', 'রামপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2461', 'Lamakazi', 'লামাকাজী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2462', 'Khajanchi', 'খাজাঞ্চী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2463', 'Alankari', 'অলংকারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2464', 'Dewkalash', 'দেওকলস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2465', 'Bishwanath', 'বিশ্বনাথ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2466', 'Doshghar', 'দশঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2467', 'Daulatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2468', 'Telikhal', 'তেলিখাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2469', 'Islampur Paschim', 'ইসলামপুর পশ্চিম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2470', 'Islampur Purba', 'ইসলামপুর পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2471', 'Isakalas', 'ইসাকলস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2472', 'Uttor Ronikhai', 'উত্তর রনিখাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2473', 'Dakkin Ronikhai', 'দক্ষিন রনিখাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2474', 'Ghilachora', 'ঘিলাছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2475', 'Fenchuganj', 'ফেঞ্চুগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2476', 'Uttar Kushiara', 'উত্তর কুশিয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2477', 'Uttar Fenchuganj', 'উত্তর ফেঞ্চুগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2478', 'Maijgaon', 'মাইজগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2479', 'Golapganj', 'গোলাপগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2480', 'Fulbari', 'ফুলবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2481', 'Lakshmipasha', 'লক্ষ্মীপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2482', 'Budhbaribazar', 'বুধবারীবাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2483', 'Dhakadakshin', 'ঢাকাদক্ষিন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2484', 'Sharifganj', 'শরিফগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2485', 'Uttar Badepasha', 'উত্তর বাদেপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2486', 'Lakshanaband', 'লক্ষনাবন্দ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2487', 'Bhadeshwar', 'ভাদেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2488', 'West Amura', 'পশ্চিম আমুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2489', 'Fothepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2490', 'Rustampur', 'রুস্তমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2491', 'Paschim Jaflong', 'পশ্চিম জাফলং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2492', 'Purba Jaflong', 'পূর্ব জাফলং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2493', 'Lengura', 'লেঙ্গুড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2494', 'Alirgaon', 'আলীরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2495', 'Nandirgaon', 'নন্দিরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2496', 'Towakul', 'তোয়াকুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2497', 'Daubari', 'ডৌবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2498', 'Nijpat', 'নিজপাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2499', 'Jaintapur', 'জৈন্তাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2500', 'Charikatha', 'চারিকাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW());