-- Import remaining BD Areas (Batch 2)
INSERT INTO bd_areas (code, "nameEn", "nameBn", type, "upazilaId", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('ARE-501', 'Chitoshiwest', 'চিতষী (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-502', 'Bishnapur', 'বিষ্ণপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-503', 'Ashikati', 'আশিকাটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-504', 'Shahmahmudpur', 'শাহ্‌ মাহমুদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-505', 'Kalyanpur', 'কল্যাণপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-506', 'Rampur', 'রামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-507', 'Maishadi', 'মৈশাদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-508', 'Tarpurchandi', 'তরপুচন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-509', 'Baghadi', 'বাগাদী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-510', 'Laxmipur Model', 'লক্ষীপুর মডেল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-511', 'Hanarchar', 'হানারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-512', 'Chandra', 'চান্দ্রা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-513', 'Rajrajeshwar', 'রাজরাজেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-514', 'Ibrahimpur', 'ইব্রাহীমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-515', 'Balia', 'বালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-516', 'Nayergaon (North)', 'নায়েরগাঁও (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-517', 'Nayergaon (South)', 'নায়েরগাঁও (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-518', 'Khadergaon', 'খাদেরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-519', 'Narayanpur', 'নারায়নপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-520', 'Upadi (South)', 'উপাদী (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-521', 'Upadi (North)', 'উপাদী (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-522', 'Rajargaon (North)', 'রাজারগাঁও (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-523', 'Bakila', 'বাকিলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-524', 'Kalocho (North)', 'কালচোঁ (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-525', 'Hajiganj Sadar', 'হাজীগঞ্জ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-526', 'Kalocho (South)', 'কালচোঁ (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-527', 'Barkul (East)', 'বড়কুল (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-528', 'Barkul (West)', 'বড়কুল (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-529', 'Hatila (East)', 'হাটিলা (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-530', 'Hatila (West)', 'হাটিলা (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-531', 'Gandharbapur (North)', 'গন্ধর্ব্যপুর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-532', 'Gandharbapur (South)', 'গন্ধর্ব্যপুর (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-533', 'Satnal', 'ষাটনল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-534', 'Banganbari', 'বাগানবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-535', 'Sadullapur', 'সাদুল্ল্যাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-536', 'Durgapur', 'দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-537', 'Kalakanda', 'কালাকান্দা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-538', 'Mohanpur', 'মোহনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-539', 'Eklaspur', 'এখলাছপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-540', 'Jahirabad', 'জহিরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-541', 'Fatehpur (East)', 'ফতেহপুর (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-542', 'Fatehpur (West)', 'ফতেহপুর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-543', 'Farajikandi', 'ফরাজীকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-544', 'Islamabad', 'ইসলামাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-545', 'Sultanabad', 'সুলতানাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-546', 'Gazra', 'গজরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-547', 'Balithuba (West)', 'বালিথুবা (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-548', 'Balithuba (East)', 'বালিথুবা (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-549', 'Subidpur (East)', 'সুবিদপুর (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-550', 'Subidpur (West)', 'সুবিদপুর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-551', 'Gupti (West)', 'গুপ্তি (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-552', 'Gupti (East)', 'গুপ্তি (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-553', 'Paikpara (North)', 'পাইকপাড়া (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-554', 'Paikpara (South)', 'পাইকপাড়া (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-555', 'Gobindapur (North)', 'গবিন্দপুর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-556', 'Gobindapur (South)', 'গবিন্দপুর (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-557', 'Chardukhia (East)', 'চরদুখিয়া (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-558', 'Chardukhia (West)', 'চরদুঃখিয়া (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-559', 'Faridgonj (South)', 'ফরিদ্গঞ্জ (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-560', 'Rupsha (South)', 'রুপসা (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-561', 'Rupsha (North)', 'রুপসা (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-562', 'Hamsadi (North)', 'হামছাদী (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-563', 'Hamsadi (South)', 'হামছাদী (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-564', 'Dalalbazar', 'দালাল বাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-565', 'Charruhita', 'চররুহিতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-566', 'Parbotinagar', 'পার্বতীনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-567', 'Bangakha', 'বাঙ্গাখাঁ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-568', 'Dattapara', 'দত্তপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-569', 'Basikpur', 'বশিকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-570', 'Chandrogonj', 'চন্দ্রগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-571', 'Nourthjoypur', 'উত্তর জয়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-572', 'Hazirpara', 'হাজিরপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-573', 'Charshahi', 'চরশাহী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-574', 'Digli', 'দিঘলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-575', 'Laharkandi', 'লাহারকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-576', 'Vobanigonj', 'ভবানীগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-577', 'Kusakhali', 'কুশাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-578', 'Sakchor', 'শাকচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-579', 'Tearigonj', 'তেয়ারীগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-580', 'Tumchor', 'টুমচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-581', 'Charramoni Mohon', 'চররমনী মোহন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-582', 'Charkalkini', 'চর কালকিনি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-583', 'Shaheberhat', 'সাহেবেরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-584', 'Char Martin', 'চর মার্টিন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-585', 'Char Folcon', 'চর ফলকন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-586', 'Patarirhat', 'পাটারীরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-587', 'Hajirhat', 'হাজিরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-588', 'Char Kadira', 'চর কাদিরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-589', 'Torabgonj', 'তোরাবগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-590', 'Charlorench', 'চর লরেঞ্চ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-591', 'North Char Ababil', 'উত্তর চর আবাবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-592', 'North Char Bangshi', 'উত্তর চর বংশী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-593', 'Char Mohana', 'চর মোহনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-594', 'Sonapur', 'সোনাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-595', 'Charpata', 'চর পাতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-596', 'Bamni', 'বামনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-597', 'South Char Bangshi', 'দক্ষিন চর বংশী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-598', 'South Char Ababil', 'দক্ষিন চর আবাবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-599', 'Raipur', 'রায়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-600', 'Keora', 'কেরোয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-601', 'Char Poragacha', 'চর পোড়াগাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-602', 'Charbadam', 'চর বাদাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-603', 'Char Abdullah', 'চর আবদুল্যাহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-604', 'Alxendar', 'আলেকজান্ডার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-605', 'Char Algi', 'চর আলগী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-606', 'Char Ramiz', 'চর রমিজ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-607', 'Borokheri', 'বড়খেড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-608', 'Chargazi', 'চরগাজী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-609', 'Kanchanpur', 'কাঞ্চনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-610', 'Noagaon', 'নোয়াগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-611', 'Bhadur', 'ভাদুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-612', 'Ichhapur', 'ইছাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-613', 'Chandipur', 'চন্ডিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-614', 'Lamchar', 'লামচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-615', 'Darbeshpur', 'দরবেশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-616', 'Karpara', 'করপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-617', 'Bholakot', 'ভোলাকোট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-618', 'Bhatra', 'ভাটরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-619', 'Rajanagar', 'রাজানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-620', 'Hosnabad', 'হোছনাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-621', 'Swanirbor Rangunia', 'স্বনির্ভর রাঙ্গুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-622', 'Mariumnagar', 'মরিয়মনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-623', 'Parua', 'পারুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-624', 'Pomra', 'পোমরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-625', 'Betagi', 'বেতাগী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-626', 'Sharafbhata', 'সরফভাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-627', 'Shilok', 'শিলক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-628', 'Chandraghona', 'চন্দ্রঘোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-629', 'Kodala', 'কোদালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-630', 'Islampur', 'ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-631', 'South Rajanagar', 'দক্ষিণ রাজানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-632', 'Lalanagar', 'লালানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-633', 'Kumira', 'কুমিরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-634', 'Banshbaria', 'বাঁশবারীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-635', 'Barabkunda', 'বারবকুন্ড', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-636', 'Bariadyala', 'বাড়িয়াডিয়ালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-637', 'Muradpur', 'মুরাদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-638', 'Saidpur', 'সাঈদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-639', 'Salimpur', 'সালিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-640', 'Sonaichhari', 'সোনাইছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-641', 'Bhatiari', 'ভাটিয়ারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-642', 'Korerhat', 'করেরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-643', 'Hinguli', 'হিংগুলি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-644', 'Jorarganj', 'জোরারগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-645', 'Dhoom', 'ধুম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-646', 'Osmanpur', 'ওসমানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-647', 'Ichakhali', 'ইছাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-648', 'Katachhara', 'কাটাছরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-649', 'Durgapur', 'দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-650', 'Mirsharai', 'মীরসরাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-651', 'Mithanala', 'মিঠানালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-652', 'Maghadia', 'মঘাদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-653', 'Khaiyachhara', 'খৈয়াছরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-654', 'Mayani', 'মায়ানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-655', 'Haitkandi', 'হাইতকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-656', 'Wahedpur', 'ওয়াহেদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-657', 'Saherkhali', 'সাহেরখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-658', 'Asia', 'আশিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-659', 'Kachuai', 'কাচুয়াই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-660', 'Kasiais', 'কাশিয়াইশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-661', 'Kusumpura', 'কুসুমপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-662', 'Kelishahar', 'কেলিশহর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-663', 'Kolagaon', 'কোলাগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-664', 'Kharana', 'খরনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-665', 'Char Patharghata', 'চর পাথরঘাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-666', 'Char Lakshya', 'চর লক্ষ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-667', 'Chanhara', 'ছনহরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-668', 'Janglukhain', 'জঙ্গলখাইন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-669', 'Jiri', 'জিরি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-670', 'Juldha', 'জুলধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-671', 'Dakkhin Bhurshi', 'দক্ষিণ ভূর্ষি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-672', 'Dhalghat', 'ধলঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-673', 'Bara Uthan', 'বড় উঠান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-674', 'Baralia', 'বরলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-675', 'Bhatikhain', 'ভাটিখাইন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-676', 'Sikalbaha', 'শিকলবাহা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-677', 'Sobhandandi', 'শোভনদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-678', 'Habilasdwi', 'হাবিলাসদ্বীপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-679', 'Haidgaon', 'হাইদগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-680', 'Rahmatpur', 'রহমতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-681', 'Harispur', 'হরিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-682', 'Kalapania', 'কালাপানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-683', 'Amanullah', 'আমানউল্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-684', 'Santoshpur', 'সন্তোষপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-685', 'Gachhua', 'গাছুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-686', 'Bauria', 'বাউরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-687', 'Haramia', 'হারামিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-688', 'Magdhara', 'মগধরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-689', 'Maitbhanga', 'মাইটভাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-690', 'Sarikait', 'সারিকাইত', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-691', 'Musapur', 'মুছাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-692', 'Azimpur', 'আজিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-693', 'Urirchar', 'উড়িরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-694', 'Pukuria', 'পুকুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-695', 'Sadhanpur', 'সাধনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-696', 'Khankhanabad', 'খানখানাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-697', 'Baharchhara', 'বাহারছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-698', 'Kalipur', 'কালীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-699', 'Bailchhari', 'বৈলছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-700', 'Katharia', 'কাথরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-701', 'Saral', 'সরল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-702', 'Silk', 'শীলকুপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-703', 'Chambal', 'চাম্বল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-704', 'Gandamara', 'গন্ডামারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-705', 'Sekherkhil', 'শেখেরখীল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-706', 'Puichhari', 'পুঁইছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-707', 'Chhanua', 'ছনুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-708', 'Kandhurkhil', 'কধুরখীল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-709', 'Pashchim Gamdandi', 'পশ্চিম গোমদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-710', 'Purba Gomdandi', 'পুর্ব গোমদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-711', 'Sakpura', 'শাকপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-712', 'Saroatali', 'সারোয়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-713', 'Popadia', 'পোপাদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-714', 'Charandwi', 'চরনদ্বীপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-715', 'Sreepur-Kharandwi', 'শ্রীপুর-খরন্দীপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-716', 'Amuchia', 'আমুচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-717', 'Ahla Karaldenga', 'আহল্লা করলডেঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-718', 'Boirag', 'বৈরাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-719', 'Barasat', 'বারশত', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-720', 'Raipur', 'রায়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-721', 'Battali', 'বটতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-722', 'Barumchara', 'বরম্নমচড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-723', 'Baroakhan', 'বারখাইন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-724', 'Anwara', 'আনোয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-725', 'Chatari', 'চাতরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-726', 'Paraikora', 'পরৈকোড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-727', 'Haildhar', 'হাইলধর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-728', 'Juidandi', 'জুঁইদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-729', 'Kanchanabad', 'কাঞ্চনাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-730', 'Joara', 'জোয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-731', 'Barkal', 'বরকল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-732', 'Barama', 'বরমা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-733', 'Bailtali', 'বৈলতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-734', 'Satbaria', 'সাতবাড়িয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-735', 'Hashimpur', 'হাশিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-736', 'Dohazari', 'দোহাজারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-737', 'Dhopachhari', 'ধোপাছড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-738', 'Charati', 'চরতী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-739', 'Khagaria', 'খাগরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-740', 'Nalua', 'নলুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-741', 'Kanchana', 'কাঞ্চনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-742', 'Amilaisi', 'আমিলাইশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-743', 'Eochiai', 'এওচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-744', 'Madarsa', 'মাদার্শা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-745', 'Dhemsa', 'ঢেমশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-746', 'Paschim Dhemsa', 'পশ্চিম ঢেমশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-747', 'Keochia', 'কেঁওচিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-748', 'Kaliais', 'কালিয়াইশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-749', 'Bazalia', 'বাজালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-750', 'Puranagar', 'পুরানগড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-751', 'Sadaha', 'ছদাহা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-752', 'Satkania', 'সাতকানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-753', 'Sonakania', 'সোনাকানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-754', 'Padua', 'পদুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-755', 'Barahatia', 'বড়হাতিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-756', 'Amirabad', 'আমিরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-757', 'Charamba', 'চরম্বা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-758', 'Kalauzan', 'কলাউজান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-759', 'Lohagara', 'লোহাগাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-760', 'Putibila', 'পুটিবিলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-761', 'Chunati', 'চুনতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-762', 'Adhunagar', 'আধুনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-763', 'Farhadabad', 'ফরহাদাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-764', 'Dhalai', 'ধলই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-765', 'Mirjapur', 'মির্জাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-766', 'Nangolmora', 'নাঙ্গলমোরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-767', 'Gomanmordan', 'গুমানমর্দ্দন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-768', 'Chipatali', 'ছিপাতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-769', 'Mekhal', 'মেখল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-770', 'Garduara', 'গড়দুয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-771', 'Fathepur', 'ফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-772', 'Chikondandi', 'চিকনদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-773', 'Uttar Madrasha', 'উত্তর মাদার্শা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-774', 'Dakkin Madrasha', 'দক্ষিন মাদার্শা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-775', 'Sikarpur', 'শিকারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-776', 'Budirchar', 'বুডিরশ্চর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-777', 'Hathazari', 'হাটহাজারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-778', 'Dharmapur', 'ধর্মপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-779', 'Baganbazar', 'বাগান বাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-780', 'Dantmara', 'দাঁতমারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-781', 'Narayanhat', 'নারায়নহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-782', 'Bhujpur', 'ভূজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-783', 'Harualchari', 'হারুয়ালছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-784', 'Paindong', 'পাইনদং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-785', 'Kanchannagor', 'কাঞ্চনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-786', 'Sunderpur', 'সুনদরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-787', 'Suabil', 'সুয়াবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-788', 'Abdullapur', 'আবদুল্লাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-789', 'Samitirhat', 'সমিতির হাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-790', 'Jafathagar', 'জাফতনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-791', 'Bokhtapur', 'বক্তপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-792', 'Roshangiri', 'রোসাংগিরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-793', 'Nanupur', 'নানুপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-794', 'Lelang', 'লেলাং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-795', 'Daulatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-796', 'Raozan', 'রাউজান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-797', 'Bagoan', 'বাগোয়ান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-798', 'Binajuri', 'বিনাজুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-799', 'Chikdair', 'চিকদাইর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-800', 'Dabua', 'ডাবুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-801', 'Purbagujra', 'পূর্ব গুজরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-802', 'Paschim Gujra', 'পশ্চিম গুজরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-803', 'Gohira', 'গহিরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-804', 'Holdia', 'হলদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-805', 'Kodolpur', 'কদলপূর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-806', 'Noapara', 'নোয়াপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-807', 'Pahartali', 'পাহাড়তলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-808', 'Urkirchar', 'উড়কিরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-809', 'Nowajushpur', 'নওয়াজিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-810', 'Char Patharghata', 'চর পাথরঘাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-811', 'Char Lakshya', 'চর লক্ষ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-812', 'Juldha', 'জুলধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-813', 'Barauthan', 'বড় উঠান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-814', 'Sikalbaha', 'শিকলবাহা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-815', 'Islamabad', 'ইসলামাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-816', 'Islampur', 'ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-817', 'Pokkhali', 'পোকখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-818', 'Eidgaon', 'ঈদগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-819', 'Jalalabad', 'জালালাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-820', 'Chowfaldandi', 'চৌফলদন্ডী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-821', 'Varuakhali', 'ভারুয়াখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-822', 'Pmkhali', 'পিএমখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-823', 'Khurushkhul', 'খুরুশকুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-824', 'Jhilongjha', 'ঝিলংঝা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-825', 'Kakhara', 'কাকারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-826', 'Kaiar Bil', 'কাইয়ার বিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-827', 'Konakhali', 'কোনাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-828', 'Khuntakhali', 'খুটাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-829', 'Chiringa', 'চিরিঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-830', 'Demusia', 'ঢেমুশিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-831', 'Dulahazara', 'ডুলাহাজারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-832', 'Paschim Bara Bheola', 'পশ্চিম বড় ভেওলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-833', 'Badarkhali', 'বদরখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-834', 'Bamobil Chari', 'বামু বিলছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-835', 'Baraitali', 'বড়ইতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-836', 'Bheola Manik Char', 'ভেওলা মানিক চর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-837', 'Saharbil', 'শাহারবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-838', 'Surajpur Manikpur', 'সুরজপুর মানিকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-839', 'Harbang', 'হারবাঙ্গ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-840', 'Fashiakhali', 'ফাঁসিয়াখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-841', 'Ali Akbar Deil', 'আলি আকবর ডেইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-842', 'Uttar Dhurung', 'উত্তর ধুরুং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-843', 'Kaiyarbil', 'কৈয়ারবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-844', 'Dakshi Dhurung', 'দক্ষিণ ধুরুং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-845', 'Baragho', 'বড়ঘোপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-846', 'Lemsikhali', 'লেমসিখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-847', 'Rajapalong', 'রাজাপালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-848', 'Jaliapalong', 'জালিয়াপালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-849', 'Holdiapalong', 'হলদিয়াপালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-850', 'Ratnapalong', 'রত্নাপালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-851', 'Palongkhali', 'পালংখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-852', 'Boro Moheshkhali', 'বড় মহেশখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-853', 'Choto Moheshkhali', 'ছোট মহেশখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-854', 'Shaplapur', 'শাপলাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-855', 'Kutubjum', 'কুতুবজোম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-856', 'Hoanak', 'হোয়ানক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-857', 'Kalarmarchhara', 'কালারমারছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-858', 'Matarbari', 'মাতারবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-859', 'Dhalghata', 'ধলঘাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-860', 'Ujantia', 'উজানটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-861', 'Taitong', 'টাইটং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-862', 'Pekua', 'পেকুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-863', 'Barabakia', 'বড় বাকিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-864', 'Magnama', 'মগনামা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-865', 'Rajakhali', 'রাজাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-866', 'Shilkhali', 'শীলখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-867', 'Fotekharkul', 'ফতেখাঁরকুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-868', 'Rajarkul', 'রাজারকুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-869', 'Rashidnagar', 'রশীদনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-870', 'Khuniapalong', 'খুনিয়াপালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-871', 'Eidghar', 'ঈদগড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-872', 'Chakmarkul', 'চাকমারকুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-873', 'Kacchapia', 'কচ্ছপিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-874', 'Kauwarkho', 'কাউয়ারখোপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-875', 'Dakkhin Mithachhari', 'দক্ষিণ মিঠাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-876', 'Jouarianala', 'জোয়ারিয়া নালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-877', 'Garjoniya', 'গর্জনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-878', 'Subrang', 'সাবরাং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-879', 'Baharchara', 'বাহারছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-880', 'Hnila', 'হ্নীলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-881', 'Whykong', 'হোয়াইক্যং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-882', 'Saintmartin', 'সেন্ট মার্টিন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-883', 'Teknaf Sadar', 'টেকনাফ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-884', 'Khagrachhari Sadar', 'খাগরাছড়ি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-885', 'Golabari', 'গোলাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-886', 'Parachara', 'পেরাছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-887', 'Kamalchari', 'কমলছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-888', 'Merung', 'মেরুং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-889', 'Boalkhali', 'বোয়ালখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-890', 'Kabakhali', 'কবাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-891', 'Dighinala', 'দিঘীনালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-892', 'Babuchara', 'বাবুছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-893', 'Logang', 'লোগাং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-894', 'Changi', 'চেংগী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-895', 'Panchari', 'পানছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-896', 'Latiban', 'লতিবান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-897', 'Dullyatali', 'দুল্যাতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-898', 'Barmachari', 'বর্মাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-899', 'Laxmichhari', 'লক্ষীছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-900', 'Bhaibonchara', 'ভাইবোনছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-901', 'Mahalchari', 'মহালছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-902', 'Mobachari', 'মুবাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-903', 'Kayanghat', 'ক্যায়াংঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-904', 'Maischari', 'মাইসছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-905', 'Manikchari', 'মানিকছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-906', 'Batnatali', 'বাটনাতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-907', 'Jogyachola', 'যোগ্যছোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-908', 'Tintahari', 'তিনটহরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-909', 'Ramgarh', 'রামগড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-910', 'Patachara', 'পাতাছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-911', 'Hafchari', 'হাফছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-912', 'Taindong', 'তাইন্দং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-913', 'Tabalchari', 'তবলছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-914', 'Barnal', 'বর্ণাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-915', 'Gomti', 'গোমতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-916', 'Balchari', 'বেলছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-917', 'Matiranga', 'মাটিরাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-918', 'Guimara', 'গুইমারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-919', 'Amtali', 'আমতলি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-920', 'Rajbila', 'রাজবিলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-921', 'Tongkaboty', 'টংকাবতী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-922', 'Suwalok', 'সুয়ালক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-923', 'Bandarban Sadar', 'বান্দরবান সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-924', 'Kuhalong', 'কুহালং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-925', 'Alikadam Sadar', 'আলীকদম সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-926', 'Chwekhyong', 'চৈক্ষ্যং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-927', 'Naikhyongchari Sadar', 'নাইক্ষ্যংছড়ি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-928', 'Gumdhum', 'ঘুমধুম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-929', 'Baishari', 'বাইশারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-930', 'Sonaychari', 'সোনাইছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-931', 'Duwchari', 'দোছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-932', 'Rowangchari Sadar', 'রোয়াংছড়ি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-933', 'Taracha', 'তারাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-934', 'Alekyong', 'আলেক্ষ্যং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-935', 'Nawapotong', 'নোয়াপতং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-936', 'Gajalia', 'গজালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-937', 'Lama Sadar', 'লামা সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-938', 'Fasiakhali', 'ফাসিয়াখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-939', 'Fythong', 'ফাইতং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-940', 'Rupushipara', 'রূপসীপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-941', 'Sarai', 'সরই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-942', 'Aziznagar', 'আজিজনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-943', 'Paind', 'পাইন্দু', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-944', 'Ruma Sadar', 'রুমা সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-945', 'Ramakreprangsa', 'রেমাক্রীপ্রাংসা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-946', 'Galanggya', 'গ্যালেংগ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-947', 'Remakre', 'রেমাক্রী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-948', 'Tind', 'তিন্দু', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-949', 'Thanchi Sadar', 'থানচি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-950', 'Balipara', 'বলিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-951', 'Rajapur', 'রাজাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-952', 'Baradhul', 'বড়ধুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-953', 'Belkuchi Sadar', 'বেলকুচি সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-954', 'Dhukuriabera', 'ধুকুরিয়া বেড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-955', 'Doulatpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-956', 'Bhangabari', 'ভাঙ্গাবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-957', 'Baghutia', 'বাঘুটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-958', 'Gharjan', 'ঘোরজান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-959', 'Khaskaulia', 'খাসকাউলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-960', 'Khaspukuria', 'খাসপুকুরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-961', 'Omarpur', 'উমারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-962', 'Sadia Chandpur', 'সদিয়া চাঁদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-963', 'Sthal', 'স্থল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-964', 'Bhadraghat', 'ভদ্রঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-965', 'Jamtail', 'জামতৈল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-966', 'Jhawail', 'ঝাঐল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-967', 'Roydaulatpur', 'রায়দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-968', 'Chalitadangha', 'চালিতাডাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-969', 'Chargirish', 'চরগিরিশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-970', 'Gandail', 'গান্ধাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-971', 'Kazipur Sadar', 'কাজিপুর সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-972', 'Khasrajbari', 'খাসরাজবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-973', 'Maijbari', 'মাইজবাড়ী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-974', 'Monsur Nagar', 'মনসুর নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-975', 'Natuarpara', 'নাটুয়ারপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-976', 'Nishchintapur', 'নিশ্চিন্তপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-977', 'Sonamukhi', 'সোনামুখী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-978', 'Subhagacha', 'শুভগাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-979', 'Tekani', 'তেকানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-980', 'Brommogacha', 'ব্রহ্মগাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-981', 'Chandaikona', 'চান্দাইকোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-982', 'Dhamainagar', 'ধামাইনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-983', 'Dhangora', 'ধানগড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-984', 'Dhubil', 'ধুবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-985', 'Ghurka', 'ঘুড়কা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-986', 'Nalka', 'নলকা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-987', 'Pangashi', 'পাঙ্গাসী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-988', 'Sonakhara', 'সোনাখাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-989', 'Beltail', 'বেলতৈল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-990', 'Jalalpur', 'জালালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-991', 'Kayempure', 'কায়েমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-992', 'Garadah', 'গাড়াদহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-993', 'Potazia', 'পোতাজিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-994', 'Rupbati', 'রূপবাটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-995', 'Gala', 'গালা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-996', 'Porzona', 'পোরজনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-997', 'Habibullah Nagar', 'হাবিবুল্লাহ নগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-998', 'Khukni', 'খুকনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-999', 'Koizuri', 'কৈজুরী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-1000', 'Sonatoni', 'সোনাতনী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW());
-- Imported: 1000 of 4540 areas
