
-- Clear existing sample data
DELETE FROM bd_areas;
DELETE FROM bd_unions;
DELETE FROM bd_upazilas;
DELETE FROM bd_districts;
DELETE FROM bd_divisions;
ALTER SEQUENCE bd_divisions_id_seq RESTART WITH 1;
ALTER SEQUENCE bd_districts_id_seq RESTART WITH 1;
ALTER SEQUENCE bd_upazilas_id_seq RESTART WITH 1;
ALTER SEQUENCE bd_unions_id_seq RESTART WITH 1;
ALTER SEQUENCE bd_areas_id_seq RESTART WITH 1;

-- Import BD Divisions (8 records)
INSERT INTO bd_divisions (code, "nameEn", "nameBn", "createdAt", "updatedAt") VALUES
('DIV-1', 'Chattagram', 'চট্টগ্রাম', NOW(), NOW()),
('DIV-2', 'Rajshahi', 'রাজশাহী', NOW(), NOW()),
('DIV-3', 'Khulna', 'খুলনা', NOW(), NOW()),
('DIV-4', 'Barisal', 'বরিশাল', NOW(), NOW()),
('DIV-5', 'Sylhet', 'সিলেট', NOW(), NOW()),
('DIV-6', 'Dhaka', 'ঢাকা', NOW(), NOW()),
('DIV-7', 'Rangpur', 'রংপুর', NOW(), NOW()),
('DIV-8', 'Mymensingh', 'ময়মনসিংহ', NOW(), NOW());

-- Import BD Districts (64 records)
INSERT INTO bd_districts (code, "nameEn", "nameBn", "divisionId", latitude, longitude, "createdAt", "updatedAt") VALUES
('DIS-1', 'Comilla', 'কুমিল্লা', 1, NULL, NULL, NOW(), NOW()),
('DIS-2', 'Feni', 'ফেনী', 1, NULL, NULL, NOW(), NOW()),
('DIS-3', 'Brahmanbaria', 'ব্রাহ্মণবাড়িয়া', 1, NULL, NULL, NOW(), NOW()),
('DIS-4', 'Rangamati', 'রাঙ্গামাটি', 1, NULL, NULL, NOW(), NOW()),
('DIS-5', 'Noakhali', 'নোয়াখালী', 1, NULL, NULL, NOW(), NOW()),
('DIS-6', 'Chandpur', 'চাঁদপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-7', 'Lakshmipur', 'লক্ষ্মীপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-8', 'Chattogram', 'চট্টগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('DIS-9', 'Coxsbazar', 'কক্সবাজার', 1, NULL, NULL, NOW(), NOW()),
('DIS-10', 'Khagrachhari', 'খাগড়াছড়ি', 1, NULL, NULL, NOW(), NOW()),
('DIS-11', 'Bandarban', 'বান্দরবান', 1, NULL, NULL, NOW(), NOW()),
('DIS-12', 'Sirajganj', 'সিরাজগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-13', 'Pabna', 'পাবনা', 1, NULL, NULL, NOW(), NOW()),
('DIS-14', 'Bogura', 'বগুড়া', 1, NULL, NULL, NOW(), NOW()),
('DIS-15', 'Rajshahi', 'রাজশাহী', 1, NULL, NULL, NOW(), NOW()),
('DIS-16', 'Natore', 'নাটোর', 1, NULL, NULL, NOW(), NOW()),
('DIS-17', 'Joypurhat', 'জয়পুরহাট', 1, NULL, NULL, NOW(), NOW()),
('DIS-18', 'Chapainawabganj', 'চাঁপাইনবাবগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-19', 'Naogaon', 'নওগাঁ', 1, NULL, NULL, NOW(), NOW()),
('DIS-20', 'Jashore', 'যশোর', 1, NULL, NULL, NOW(), NOW()),
('DIS-21', 'Satkhira', 'সাতক্ষীরা', 1, NULL, NULL, NOW(), NOW()),
('DIS-22', 'Meherpur', 'মেহেরপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-23', 'Narail', 'নড়াইল', 1, NULL, NULL, NOW(), NOW()),
('DIS-24', 'Chuadanga', 'চুয়াডাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('DIS-25', 'Kushtia', 'কুষ্টিয়া', 1, NULL, NULL, NOW(), NOW()),
('DIS-26', 'Magura', 'মাগুরা', 1, NULL, NULL, NOW(), NOW()),
('DIS-27', 'Khulna', 'খুলনা', 1, NULL, NULL, NOW(), NOW()),
('DIS-28', 'Bagerhat', 'বাগেরহাট', 1, NULL, NULL, NOW(), NOW()),
('DIS-29', 'Jhenaidah', 'ঝিনাইদহ', 1, NULL, NULL, NOW(), NOW()),
('DIS-30', 'Jhalakathi', 'ঝালকাঠি', 1, NULL, NULL, NOW(), NOW()),
('DIS-31', 'Patuakhali', 'পটুয়াখালী', 1, NULL, NULL, NOW(), NOW()),
('DIS-32', 'Pirojpur', 'পিরোজপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-33', 'Barisal', 'বরিশাল', 1, NULL, NULL, NOW(), NOW()),
('DIS-34', 'Bhola', 'ভোলা', 1, NULL, NULL, NOW(), NOW()),
('DIS-35', 'Barguna', 'বরগুনা', 1, NULL, NULL, NOW(), NOW()),
('DIS-36', 'Sylhet', 'সিলেট', 1, NULL, NULL, NOW(), NOW()),
('DIS-37', 'Moulvibazar', 'মৌলভীবাজার', 1, NULL, NULL, NOW(), NOW()),
('DIS-38', 'Habiganj', 'হবিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-39', 'Sunamganj', 'সুনামগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-40', 'Narsingdi', 'নরসিংদী', 1, NULL, NULL, NOW(), NOW()),
('DIS-41', 'Gazipur', 'গাজীপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-42', 'Shariatpur', 'শরীয়তপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-43', 'Narayanganj', 'নারায়ণগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-44', 'Tangail', 'টাঙ্গাইল', 1, NULL, NULL, NOW(), NOW()),
('DIS-45', 'Kishoreganj', 'কিশোরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-46', 'Manikganj', 'মানিকগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-47', 'Dhaka', 'ঢাকা', 1, NULL, NULL, NOW(), NOW()),
('DIS-48', 'Munshiganj', 'মুন্সিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-49', 'Rajbari', 'রাজবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('DIS-50', 'Madaripur', 'মাদারীপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-51', 'Gopalganj', 'গোপালগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('DIS-52', 'Faridpur', 'ফরিদপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-53', 'Panchagarh', 'পঞ্চগড়', 1, NULL, NULL, NOW(), NOW()),
('DIS-54', 'Dinajpur', 'দিনাজপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-55', 'Lalmonirhat', 'লালমনিরহাট', 1, NULL, NULL, NOW(), NOW()),
('DIS-56', 'Nilphamari', 'নীলফামারী', 1, NULL, NULL, NOW(), NOW()),
('DIS-57', 'Gaibandha', 'গাইবান্ধা', 1, NULL, NULL, NOW(), NOW()),
('DIS-58', 'Thakurgaon', 'ঠাকুরগাঁও', 1, NULL, NULL, NOW(), NOW()),
('DIS-59', 'Rangpur', 'রংপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-60', 'Kurigram', 'কুড়িগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('DIS-61', 'Sherpur', 'শেরপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-62', 'Mymensingh', 'ময়মনসিংহ', 1, NULL, NULL, NOW(), NOW()),
('DIS-63', 'Jamalpur', 'জামালপুর', 1, NULL, NULL, NOW(), NOW()),
('DIS-64', 'Netrokona', 'নেত্রকোণা', 1, NULL, NULL, NOW(), NOW());

-- Import BD Upazilas (495 records)
INSERT INTO bd_upazilas (code, "nameEn", "nameBn", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('UPA-1', 'Debidwar', 'দেবিদ্বার', 1, NULL, NULL, NOW(), NOW()),
('UPA-2', 'Barura', 'বরুড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-3', 'Brahmanpara', 'ব্রাহ্মণপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-4', 'Chandina', 'চান্দিনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-5', 'Chauddagram', 'চৌদ্দগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-6', 'Daudkandi', 'দাউদকান্দি', 1, NULL, NULL, NOW(), NOW()),
('UPA-7', 'Homna', 'হোমনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-8', 'Laksam', 'লাকসাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-9', 'Muradnagar', 'মুরাদনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-10', 'Nangalkot', 'নাঙ্গলকোট', 1, NULL, NULL, NOW(), NOW()),
('UPA-11', 'Comilla Sadar', 'কুমিল্লা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-12', 'Meghna', 'মেঘনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-13', 'Monohargonj', 'মনোহরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-14', 'Sadarsouth', 'সদর দক্ষিণ', 1, NULL, NULL, NOW(), NOW()),
('UPA-15', 'Titas', 'তিতাস', 1, NULL, NULL, NOW(), NOW()),
('UPA-16', 'Burichang', 'বুড়িচং', 1, NULL, NULL, NOW(), NOW()),
('UPA-17', 'Lalmai', 'লালমাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-18', 'Chhagalnaiya', 'ছাগলনাইয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-19', 'Feni Sadar', 'ফেনী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-20', 'Sonagazi', 'সোনাগাজী', 1, NULL, NULL, NOW(), NOW()),
('UPA-21', 'Fulgazi', 'ফুলগাজী', 1, NULL, NULL, NOW(), NOW()),
('UPA-22', 'Parshuram', 'পরশুরাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-23', 'Daganbhuiyan', 'দাগনভূঞা', 1, NULL, NULL, NOW(), NOW()),
('UPA-24', 'Brahmanbaria Sadar', 'ব্রাহ্মণবাড়িয়া সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-25', 'Kasba', 'কসবা', 1, NULL, NULL, NOW(), NOW()),
('UPA-26', 'Nasirnagar', 'নাসিরনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-27', 'Sarail', 'সরাইল', 1, NULL, NULL, NOW(), NOW()),
('UPA-28', 'Ashuganj', 'আশুগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-29', 'Akhaura', 'আখাউড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-30', 'Nabinagar', 'নবীনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-31', 'Bancharampur', 'বাঞ্ছারামপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-32', 'Bijoynagar', 'বিজয়নগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-33', 'Rangamati Sadar', 'রাঙ্গামাটি সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-34', 'Kaptai', 'কাপ্তাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-35', 'Kawkhali', 'কাউখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-36', 'Baghaichari', 'বাঘাইছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-37', 'Barkal', 'বরকল', 1, NULL, NULL, NOW(), NOW()),
('UPA-38', 'Langadu', 'লংগদু', 1, NULL, NULL, NOW(), NOW()),
('UPA-39', 'Rajasthali', 'রাজস্থলী', 1, NULL, NULL, NOW(), NOW()),
('UPA-40', 'Belaichari', 'বিলাইছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-41', 'Juraichari', 'জুরাছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-42', 'Naniarchar', 'নানিয়ারচর', 1, NULL, NULL, NOW(), NOW()),
('UPA-43', 'Noakhali Sadar', 'নোয়াখালী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-44', 'Companiganj', 'কোম্পানীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-45', 'Begumganj', 'বেগমগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-46', 'Hatia', 'হাতিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-47', 'Subarnachar', 'সুবর্ণচর', 1, NULL, NULL, NOW(), NOW()),
('UPA-48', 'Kabirhat', 'কবিরহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-49', 'Senbug', 'সেনবাগ', 1, NULL, NULL, NOW(), NOW()),
('UPA-50', 'Chatkhil', 'চাটখিল', 1, NULL, NULL, NOW(), NOW()),
('UPA-51', 'Sonaimori', 'সোনাইমুড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-52', 'Haimchar', 'হাইমচর', 1, NULL, NULL, NOW(), NOW()),
('UPA-53', 'Kachua', 'কচুয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-54', 'Shahrasti', 'শাহরাস্তি	', 1, NULL, NULL, NOW(), NOW()),
('UPA-55', 'Chandpur Sadar', 'চাঁদপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-56', 'Matlab South', 'মতলব দক্ষিণ', 1, NULL, NULL, NOW(), NOW()),
('UPA-57', 'Hajiganj', 'হাজীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-58', 'Matlab North', 'মতলব উত্তর', 1, NULL, NULL, NOW(), NOW()),
('UPA-59', 'Faridgonj', 'ফরিদগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-60', 'Lakshmipur Sadar', 'লক্ষ্মীপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-61', 'Kamalnagar', 'কমলনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-62', 'Raipur', 'রায়পুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-63', 'Ramgati', 'রামগতি', 1, NULL, NULL, NOW(), NOW()),
('UPA-64', 'Ramganj', 'রামগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-65', 'Rangunia', 'রাঙ্গুনিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-66', 'Sitakunda', 'সীতাকুন্ড', 1, NULL, NULL, NOW(), NOW()),
('UPA-67', 'Mirsharai', 'মীরসরাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-68', 'Patiya', 'পটিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-69', 'Sandwip', 'সন্দ্বীপ', 1, NULL, NULL, NOW(), NOW()),
('UPA-70', 'Banshkhali', 'বাঁশখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-71', 'Boalkhali', 'বোয়ালখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-72', 'Anwara', 'আনোয়ারা', 1, NULL, NULL, NOW(), NOW()),
('UPA-73', 'Chandanaish', 'চন্দনাইশ', 1, NULL, NULL, NOW(), NOW()),
('UPA-74', 'Satkania', 'সাতকানিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-75', 'Lohagara', 'লোহাগাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-76', 'Hathazari', 'হাটহাজারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-77', 'Fatikchhari', 'ফটিকছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-78', 'Raozan', 'রাউজান', 1, NULL, NULL, NOW(), NOW()),
('UPA-79', 'Karnafuli', 'কর্ণফুলী', 1, NULL, NULL, NOW(), NOW()),
('UPA-80', 'Coxsbazar Sadar', 'কক্সবাজার সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-81', 'Chakaria', 'চকরিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-82', 'Kutubdia', 'কুতুবদিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-83', 'Ukhiya', 'উখিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-84', 'Moheshkhali', 'মহেশখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-85', 'Pekua', 'পেকুয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-86', 'Ramu', 'রামু', 1, NULL, NULL, NOW(), NOW()),
('UPA-87', 'Teknaf', 'টেকনাফ', 1, NULL, NULL, NOW(), NOW()),
('UPA-88', 'Khagrachhari Sadar', 'খাগড়াছড়ি সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-89', 'Dighinala', 'দিঘীনালা', 1, NULL, NULL, NOW(), NOW()),
('UPA-90', 'Panchari', 'পানছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-91', 'Laxmichhari', 'লক্ষীছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-92', 'Mohalchari', 'মহালছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-93', 'Manikchari', 'মানিকছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-94', 'Ramgarh', 'রামগড়', 1, NULL, NULL, NOW(), NOW()),
('UPA-95', 'Matiranga', 'মাটিরাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('UPA-96', 'Guimara', 'গুইমারা', 1, NULL, NULL, NOW(), NOW()),
('UPA-97', 'Bandarban Sadar', 'বান্দরবান সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-98', 'Alikadam', 'আলীকদম', 1, NULL, NULL, NOW(), NOW()),
('UPA-99', 'Naikhongchhari', 'নাইক্ষ্যংছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-100', 'Rowangchhari', 'রোয়াংছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-101', 'Lama', 'লামা', 1, NULL, NULL, NOW(), NOW()),
('UPA-102', 'Ruma', 'রুমা', 1, NULL, NULL, NOW(), NOW()),
('UPA-103', 'Thanchi', 'থানচি', 1, NULL, NULL, NOW(), NOW()),
('UPA-104', 'Belkuchi', 'বেলকুচি', 1, NULL, NULL, NOW(), NOW()),
('UPA-105', 'Chauhali', 'চৌহালি', 1, NULL, NULL, NOW(), NOW()),
('UPA-106', 'Kamarkhand', 'কামারখন্দ', 1, NULL, NULL, NOW(), NOW()),
('UPA-107', 'Kazipur', 'কাজীপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-108', 'Raigonj', 'রায়গঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-109', 'Shahjadpur', 'শাহজাদপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-110', 'Sirajganj Sadar', 'সিরাজগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-111', 'Tarash', 'তাড়াশ', 1, NULL, NULL, NOW(), NOW()),
('UPA-112', 'Ullapara', 'উল্লাপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-113', 'Sujanagar', 'সুজানগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-114', 'Ishurdi', 'ঈশ্বরদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-115', 'Bhangura', 'ভাঙ্গুড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-116', 'Pabna Sadar', 'পাবনা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-117', 'Bera', 'বেড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-118', 'Atghoria', 'আটঘরিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-119', 'Chatmohar', 'চাটমোহর', 1, NULL, NULL, NOW(), NOW()),
('UPA-120', 'Santhia', 'সাঁথিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-121', 'Faridpur', 'ফরিদপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-122', 'Kahaloo', 'কাহালু', 1, NULL, NULL, NOW(), NOW()),
('UPA-123', 'Bogra Sadar', 'বগুড়া সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-124', 'Shariakandi', 'সারিয়াকান্দি', 1, NULL, NULL, NOW(), NOW()),
('UPA-125', 'Shajahanpur', 'শাজাহানপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-126', 'Dupchanchia', 'দুপচাচিঁয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-127', 'Adamdighi', 'আদমদিঘি', 1, NULL, NULL, NOW(), NOW()),
('UPA-128', 'Nondigram', 'নন্দিগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-129', 'Sonatala', 'সোনাতলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-130', 'Dhunot', 'ধুনট', 1, NULL, NULL, NOW(), NOW()),
('UPA-131', 'Gabtali', 'গাবতলী', 1, NULL, NULL, NOW(), NOW()),
('UPA-132', 'Sherpur', 'শেরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-133', 'Shibganj', 'শিবগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-134', 'Paba', 'পবা', 1, NULL, NULL, NOW(), NOW()),
('UPA-135', 'Durgapur', 'দুর্গাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-136', 'Mohonpur', 'মোহনপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-137', 'Charghat', 'চারঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-138', 'Puthia', 'পুঠিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-139', 'Bagha', 'বাঘা', 1, NULL, NULL, NOW(), NOW()),
('UPA-140', 'Godagari', 'গোদাগাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-141', 'Tanore', 'তানোর', 1, NULL, NULL, NOW(), NOW()),
('UPA-142', 'Bagmara', 'বাগমারা', 1, NULL, NULL, NOW(), NOW()),
('UPA-143', 'Natore Sadar', 'নাটোর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-144', 'Singra', 'সিংড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-145', 'Baraigram', 'বড়াইগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-146', 'Bagatipara', 'বাগাতিপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-147', 'Lalpur', 'লালপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-148', 'Gurudaspur', 'গুরুদাসপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-149', 'Naldanga', 'নলডাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('UPA-150', 'Akkelpur', 'আক্কেলপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-151', 'Kalai', 'কালাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-152', 'Khetlal', 'ক্ষেতলাল', 1, NULL, NULL, NOW(), NOW()),
('UPA-153', 'Panchbibi', 'পাঁচবিবি', 1, NULL, NULL, NOW(), NOW()),
('UPA-154', 'Joypurhat Sadar', 'জয়পুরহাট সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-155', 'Chapainawabganj Sadar', 'চাঁপাইনবাবগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-156', 'Gomostapur', 'গোমস্তাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-157', 'Nachol', 'নাচোল', 1, NULL, NULL, NOW(), NOW()),
('UPA-158', 'Bholahat', 'ভোলাহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-159', 'Shibganj', 'শিবগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-160', 'Mohadevpur', 'মহাদেবপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-161', 'Badalgachi', 'বদলগাছী', 1, NULL, NULL, NOW(), NOW()),
('UPA-162', 'Patnitala', 'পত্নিতলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-163', 'Dhamoirhat', 'ধামইরহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-164', 'Niamatpur', 'নিয়ামতপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-165', 'Manda', 'মান্দা', 1, NULL, NULL, NOW(), NOW()),
('UPA-166', 'Atrai', 'আত্রাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-167', 'Raninagar', 'রাণীনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-168', 'Naogaon Sadar', 'নওগাঁ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-169', 'Porsha', 'পোরশা', 1, NULL, NULL, NOW(), NOW()),
('UPA-170', 'Sapahar', 'সাপাহার', 1, NULL, NULL, NOW(), NOW()),
('UPA-171', 'Manirampur', 'মণিরামপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-172', 'Abhaynagar', 'অভয়নগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-173', 'Bagherpara', 'বাঘারপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-174', 'Chougachha', 'চৌগাছা', 1, NULL, NULL, NOW(), NOW()),
('UPA-175', 'Jhikargacha', 'ঝিকরগাছা', 1, NULL, NULL, NOW(), NOW()),
('UPA-176', 'Keshabpur', 'কেশবপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-177', 'Jessore Sadar', 'যশোর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-178', 'Sharsha', 'শার্শা', 1, NULL, NULL, NOW(), NOW()),
('UPA-179', 'Assasuni', 'আশাশুনি', 1, NULL, NULL, NOW(), NOW()),
('UPA-180', 'Debhata', 'দেবহাটা', 1, NULL, NULL, NOW(), NOW()),
('UPA-181', 'Kalaroa', 'কলারোয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-182', 'Satkhira Sadar', 'সাতক্ষীরা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-183', 'Shyamnagar', 'শ্যামনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-184', 'Tala', 'তালা', 1, NULL, NULL, NOW(), NOW()),
('UPA-185', 'Kaliganj', 'কালিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-186', 'Mujibnagar', 'মুজিবনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-187', 'Meherpur Sadar', 'মেহেরপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-188', 'Gangni', 'গাংনী', 1, NULL, NULL, NOW(), NOW()),
('UPA-189', 'Narail Sadar', 'নড়াইল সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-190', 'Lohagara', 'লোহাগড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-191', 'Kalia', 'কালিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-192', 'Chuadanga Sadar', 'চুয়াডাঙ্গা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-193', 'Alamdanga', 'আলমডাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('UPA-194', 'Damurhuda', 'দামুড়হুদা', 1, NULL, NULL, NOW(), NOW()),
('UPA-195', 'Jibannagar', 'জীবননগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-196', 'Kushtia Sadar', 'কুষ্টিয়া সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-197', 'Kumarkhali', 'কুমারখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-198', 'Khoksa', 'খোকসা', 1, NULL, NULL, NOW(), NOW()),
('UPA-199', 'Mirpur', 'মিরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-200', 'Daulatpur', 'দৌলতপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-201', 'Bheramara', 'ভেড়ামারা', 1, NULL, NULL, NOW(), NOW()),
('UPA-202', 'Shalikha', 'শালিখা', 1, NULL, NULL, NOW(), NOW()),
('UPA-203', 'Sreepur', 'শ্রীপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-204', 'Magura Sadar', 'মাগুরা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-205', 'Mohammadpur', 'মহম্মদপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-206', 'Paikgasa', 'পাইকগাছা', 1, NULL, NULL, NOW(), NOW()),
('UPA-207', 'Fultola', 'ফুলতলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-208', 'Digholia', 'দিঘলিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-209', 'Rupsha', 'রূপসা', 1, NULL, NULL, NOW(), NOW()),
('UPA-210', 'Terokhada', 'তেরখাদা', 1, NULL, NULL, NOW(), NOW()),
('UPA-211', 'Dumuria', 'ডুমুরিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-212', 'Botiaghata', 'বটিয়াঘাটা', 1, NULL, NULL, NOW(), NOW()),
('UPA-213', 'Dakop', 'দাকোপ', 1, NULL, NULL, NOW(), NOW()),
('UPA-214', 'Koyra', 'কয়রা', 1, NULL, NULL, NOW(), NOW()),
('UPA-215', 'Fakirhat', 'ফকিরহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-216', 'Bagerhat Sadar', 'বাগেরহাট সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-217', 'Mollahat', 'মোল্লাহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-218', 'Sarankhola', 'শরণখোলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-219', 'Rampal', 'রামপাল', 1, NULL, NULL, NOW(), NOW()),
('UPA-220', 'Morrelganj', 'মোড়েলগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-221', 'Kachua', 'কচুয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-222', 'Mongla', 'মোংলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-223', 'Chitalmari', 'চিতলমারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-224', 'Jhenaidah Sadar', 'ঝিনাইদহ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-225', 'Shailkupa', 'শৈলকুপা', 1, NULL, NULL, NOW(), NOW()),
('UPA-226', 'Harinakundu', 'হরিণাকুন্ডু', 1, NULL, NULL, NOW(), NOW()),
('UPA-227', 'Kaliganj', 'কালীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-228', 'Kotchandpur', 'কোটচাঁদপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-229', 'Moheshpur', 'মহেশপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-230', 'Jhalakathi Sadar', 'ঝালকাঠি সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-231', 'Kathalia', 'কাঠালিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-232', 'Nalchity', 'নলছিটি', 1, NULL, NULL, NOW(), NOW()),
('UPA-233', 'Rajapur', 'রাজাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-234', 'Bauphal', 'বাউফল', 1, NULL, NULL, NOW(), NOW()),
('UPA-235', 'Patuakhali Sadar', 'পটুয়াখালী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-236', 'Dumki', 'দুমকি', 1, NULL, NULL, NOW(), NOW()),
('UPA-237', 'Dashmina', 'দশমিনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-238', 'Kalapara', 'কলাপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-239', 'Mirzaganj', 'মির্জাগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-240', 'Galachipa', 'গলাচিপা', 1, NULL, NULL, NOW(), NOW()),
('UPA-241', 'Rangabali', 'রাঙ্গাবালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-242', 'Pirojpur Sadar', 'পিরোজপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-243', 'Nazirpur', 'নাজিরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-244', 'Kawkhali', 'কাউখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-245', 'Indurkani', 'ইন্দুরকানী', 1, NULL, NULL, NOW(), NOW()),
('UPA-246', 'Bhandaria', 'ভান্ডারিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-247', 'Mathbaria', 'মঠবাড়ীয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-248', 'Nesarabad', 'নেছারাবাদ', 1, NULL, NULL, NOW(), NOW()),
('UPA-249', 'Barisal Sadar', 'বরিশাল সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-250', 'Bakerganj', 'বাকেরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-251', 'Babuganj', 'বাবুগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-252', 'Wazirpur', 'উজিরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-253', 'Banaripara', 'বানারীপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-254', 'Gournadi', 'গৌরনদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-255', 'Agailjhara', 'আগৈলঝাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-256', 'Mehendiganj', 'মেহেন্দিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-257', 'Muladi', 'মুলাদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-258', 'Hizla', 'হিজলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-259', 'Bhola Sadar', 'ভোলা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-260', 'Borhanuddin', 'বোরহানউদ্দিন', 1, NULL, NULL, NOW(), NOW()),
('UPA-261', 'Charfesson', 'চরফ্যাশন', 1, NULL, NULL, NOW(), NOW()),
('UPA-262', 'Doulatkhan', 'দৌলতখান', 1, NULL, NULL, NOW(), NOW()),
('UPA-263', 'Monpura', 'মনপুরা', 1, NULL, NULL, NOW(), NOW()),
('UPA-264', 'Tazumuddin', 'তজুমদ্দিন', 1, NULL, NULL, NOW(), NOW()),
('UPA-265', 'Lalmohan', 'লালমোহন', 1, NULL, NULL, NOW(), NOW()),
('UPA-266', 'Amtali', 'আমতলী', 1, NULL, NULL, NOW(), NOW()),
('UPA-267', 'Barguna Sadar', 'বরগুনা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-268', 'Betagi', 'বেতাগী', 1, NULL, NULL, NOW(), NOW()),
('UPA-269', 'Bamna', 'বামনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-270', 'Pathorghata', 'পাথরঘাটা', 1, NULL, NULL, NOW(), NOW()),
('UPA-271', 'Taltali', 'তালতলি', 1, NULL, NULL, NOW(), NOW()),
('UPA-272', 'Balaganj', 'বালাগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-273', 'Beanibazar', 'বিয়ানীবাজার', 1, NULL, NULL, NOW(), NOW()),
('UPA-274', 'Bishwanath', 'বিশ্বনাথ', 1, NULL, NULL, NOW(), NOW()),
('UPA-275', 'Companiganj', 'কোম্পানীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-276', 'Fenchuganj', 'ফেঞ্চুগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-277', 'Golapganj', 'গোলাপগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-278', 'Gowainghat', 'গোয়াইনঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-279', 'Jaintiapur', 'জৈন্তাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-280', 'Kanaighat', 'কানাইঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-281', 'Sylhet Sadar', 'সিলেট সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-282', 'Zakiganj', 'জকিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-283', 'Dakshinsurma', 'দক্ষিণ সুরমা', 1, NULL, NULL, NOW(), NOW()),
('UPA-284', 'Osmaninagar', 'ওসমানী নগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-285', 'Barlekha', 'বড়লেখা', 1, NULL, NULL, NOW(), NOW()),
('UPA-286', 'Kamolganj', 'কমলগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-287', 'Kulaura', 'কুলাউড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-288', 'Moulvibazar Sadar', 'মৌলভীবাজার সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-289', 'Rajnagar', 'রাজনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-290', 'Sreemangal', 'শ্রীমঙ্গল', 1, NULL, NULL, NOW(), NOW()),
('UPA-291', 'Juri', 'জুড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-292', 'Nabiganj', 'নবীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-293', 'Bahubal', 'বাহুবল', 1, NULL, NULL, NOW(), NOW()),
('UPA-294', 'Ajmiriganj', 'আজমিরীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-295', 'Baniachong', 'বানিয়াচং', 1, NULL, NULL, NOW(), NOW()),
('UPA-296', 'Lakhai', 'লাখাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-297', 'Chunarughat', 'চুনারুঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-298', 'Habiganj Sadar', 'হবিগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-299', 'Madhabpur', 'মাধবপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-300', 'Sunamganj Sadar', 'সুনামগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-301', 'Shantiganj', 'শান্তিগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-302', 'Bishwambarpur', 'বিশ্বম্ভরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-303', 'Chhatak', 'ছাতক', 1, NULL, NULL, NOW(), NOW()),
('UPA-304', 'Jagannathpur', 'জগন্নাথপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-305', 'Dowarabazar', 'দোয়ারাবাজার', 1, NULL, NULL, NOW(), NOW()),
('UPA-306', 'Tahirpur', 'তাহিরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-307', 'Dharmapasha', 'ধর্মপাশা', 1, NULL, NULL, NOW(), NOW()),
('UPA-308', 'Jamalganj', 'জামালগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-309', 'Shalla', 'শাল্লা', 1, NULL, NULL, NOW(), NOW()),
('UPA-310', 'Derai', 'দিরাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-311', 'Belabo', 'বেলাবো', 1, NULL, NULL, NOW(), NOW()),
('UPA-312', 'Monohardi', 'মনোহরদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-313', 'Narsingdi Sadar', 'নরসিংদী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-314', 'Palash', 'পলাশ', 1, NULL, NULL, NOW(), NOW()),
('UPA-315', 'Raipura', 'রায়পুরা', 1, NULL, NULL, NOW(), NOW()),
('UPA-316', 'Shibpur', 'শিবপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-317', 'Kaliganj', 'কালীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-318', 'Kaliakair', 'কালিয়াকৈর', 1, NULL, NULL, NOW(), NOW()),
('UPA-319', 'Kapasia', 'কাপাসিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-320', 'Gazipur Sadar', 'গাজীপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-321', 'Sreepur', 'শ্রীপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-322', 'Shariatpur Sadar', 'শরিয়তপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-323', 'Naria', 'নড়িয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-324', 'Zajira', 'জাজিরা', 1, NULL, NULL, NOW(), NOW()),
('UPA-325', 'Gosairhat', 'গোসাইরহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-326', 'Bhedarganj', 'ভেদরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-327', 'Damudya', 'ডামুড্যা', 1, NULL, NULL, NOW(), NOW()),
('UPA-328', 'Araihazar', 'আড়াইহাজার', 1, NULL, NULL, NOW(), NOW()),
('UPA-329', 'Bandar', 'বন্দর', 1, NULL, NULL, NOW(), NOW()),
('UPA-330', 'Narayanganj Sadar', 'নারায়নগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-331', 'Rupganj', 'রূপগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-332', 'Sonargaon', 'সোনারগাঁ', 1, NULL, NULL, NOW(), NOW()),
('UPA-333', 'Basail', 'বাসাইল', 1, NULL, NULL, NOW(), NOW()),
('UPA-334', 'Bhuapur', 'ভুয়াপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-335', 'Delduar', 'দেলদুয়ার', 1, NULL, NULL, NOW(), NOW()),
('UPA-336', 'Ghatail', 'ঘাটাইল', 1, NULL, NULL, NOW(), NOW()),
('UPA-337', 'Gopalpur', 'গোপালপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-338', 'Madhupur', 'মধুপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-339', 'Mirzapur', 'মির্জাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-340', 'Nagarpur', 'নাগরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-341', 'Sakhipur', 'সখিপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-342', 'Tangail Sadar', 'টাঙ্গাইল সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-343', 'Kalihati', 'কালিহাতী', 1, NULL, NULL, NOW(), NOW()),
('UPA-344', 'Dhanbari', 'ধনবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-345', 'Itna', 'ইটনা', 1, NULL, NULL, NOW(), NOW()),
('UPA-346', 'Katiadi', 'কটিয়াদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-347', 'Bhairab', 'ভৈরব', 1, NULL, NULL, NOW(), NOW()),
('UPA-348', 'Tarail', 'তাড়াইল', 1, NULL, NULL, NOW(), NOW()),
('UPA-349', 'Hossainpur', 'হোসেনপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-350', 'Pakundia', 'পাকুন্দিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-351', 'Kuliarchar', 'কুলিয়ারচর', 1, NULL, NULL, NOW(), NOW()),
('UPA-352', 'Kishoreganj Sadar', 'কিশোরগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-353', 'Karimgonj', 'করিমগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-354', 'Bajitpur', 'বাজিতপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-355', 'Austagram', 'অষ্টগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-356', 'Mithamoin', 'মিঠামইন', 1, NULL, NULL, NOW(), NOW()),
('UPA-357', 'Nikli', 'নিকলী', 1, NULL, NULL, NOW(), NOW()),
('UPA-358', 'Harirampur', 'হরিরামপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-359', 'Saturia', 'সাটুরিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-360', 'Manikganj Sadar', 'মানিকগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-361', 'Gior', 'ঘিওর', 1, NULL, NULL, NOW(), NOW()),
('UPA-362', 'Shibaloy', 'শিবালয়', 1, NULL, NULL, NOW(), NOW()),
('UPA-363', 'Doulatpur', 'দৌলতপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-364', 'Singiar', 'সিংগাইর', 1, NULL, NULL, NOW(), NOW()),
('UPA-365', 'Savar', 'সাভার', 1, NULL, NULL, NOW(), NOW()),
('UPA-366', 'Dhamrai', 'ধামরাই', 1, NULL, NULL, NOW(), NOW()),
('UPA-367', 'Keraniganj', 'কেরাণীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-368', 'Nawabganj', 'নবাবগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-369', 'Dohar', 'দোহার', 1, NULL, NULL, NOW(), NOW()),
('UPA-370', 'Munshiganj Sadar', 'মুন্সিগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-371', 'Sreenagar', 'শ্রীনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-372', 'Sirajdikhan', 'সিরাজদিখান', 1, NULL, NULL, NOW(), NOW()),
('UPA-373', 'Louhajanj', 'লৌহজং', 1, NULL, NULL, NOW(), NOW()),
('UPA-374', 'Gajaria', 'গজারিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-375', 'Tongibari', 'টংগীবাড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-376', 'Rajbari Sadar', 'রাজবাড়ী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-377', 'Goalanda', 'গোয়ালন্দ', 1, NULL, NULL, NOW(), NOW()),
('UPA-378', 'Pangsa', 'পাংশা', 1, NULL, NULL, NOW(), NOW()),
('UPA-379', 'Baliakandi', 'বালিয়াকান্দি', 1, NULL, NULL, NOW(), NOW()),
('UPA-380', 'Kalukhali', 'কালুখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-381', 'Madaripur Sadar', 'মাদারীপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-382', 'Shibchar', 'শিবচর', 1, NULL, NULL, NOW(), NOW()),
('UPA-383', 'Kalkini', 'কালকিনি', 1, NULL, NULL, NOW(), NOW()),
('UPA-384', 'Rajoir', 'রাজৈর', 1, NULL, NULL, NOW(), NOW()),
('UPA-385', 'Gopalganj Sadar', 'গোপালগঞ্জ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-386', 'Kashiani', 'কাশিয়ানী', 1, NULL, NULL, NOW(), NOW()),
('UPA-387', 'Tungipara', 'টুংগীপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-388', 'Kotalipara', 'কোটালীপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-389', 'Muksudpur', 'মুকসুদপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-390', 'Faridpur Sadar', 'ফরিদপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-391', 'Alfadanga', 'আলফাডাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('UPA-392', 'Boalmari', 'বোয়ালমারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-393', 'Sadarpur', 'সদরপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-394', 'Nagarkanda', 'নগরকান্দা', 1, NULL, NULL, NOW(), NOW()),
('UPA-395', 'Bhanga', 'ভাঙ্গা', 1, NULL, NULL, NOW(), NOW()),
('UPA-396', 'Charbhadrasan', 'চরভদ্রাসন', 1, NULL, NULL, NOW(), NOW()),
('UPA-397', 'Madhukhali', 'মধুখালী', 1, NULL, NULL, NOW(), NOW()),
('UPA-398', 'Saltha', 'সালথা', 1, NULL, NULL, NOW(), NOW()),
('UPA-399', 'Panchagarh Sadar', 'পঞ্চগড় সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-400', 'Debiganj', 'দেবীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-401', 'Boda', 'বোদা', 1, NULL, NULL, NOW(), NOW()),
('UPA-402', 'Atwari', 'আটোয়ারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-403', 'Tetulia', 'তেতুলিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-404', 'Nawabganj', 'নবাবগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-405', 'Birganj', 'বীরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-406', 'Ghoraghat', 'ঘোড়াঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-407', 'Birampur', 'বিরামপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-408', 'Parbatipur', 'পার্বতীপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-409', 'Bochaganj', 'বোচাগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-410', 'Kaharol', 'কাহারোল', 1, NULL, NULL, NOW(), NOW()),
('UPA-411', 'Fulbari', 'ফুলবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-412', 'Dinajpur Sadar', 'দিনাজপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-413', 'Hakimpur', 'হাকিমপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-414', 'Khansama', 'খানসামা', 1, NULL, NULL, NOW(), NOW()),
('UPA-415', 'Birol', 'বিরল', 1, NULL, NULL, NOW(), NOW()),
('UPA-416', 'Chirirbandar', 'চিরিরবন্দর', 1, NULL, NULL, NOW(), NOW()),
('UPA-417', 'Lalmonirhat Sadar', 'লালমনিরহাট সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-418', 'Kaliganj', 'কালীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-419', 'Hatibandha', 'হাতীবান্ধা', 1, NULL, NULL, NOW(), NOW()),
('UPA-420', 'Patgram', 'পাটগ্রাম', 1, NULL, NULL, NOW(), NOW()),
('UPA-421', 'Aditmari', 'আদিতমারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-422', 'Syedpur', 'সৈয়দপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-423', 'Domar', 'ডোমার', 1, NULL, NULL, NOW(), NOW()),
('UPA-424', 'Dimla', 'ডিমলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-425', 'Jaldhaka', 'জলঢাকা', 1, NULL, NULL, NOW(), NOW()),
('UPA-426', 'Kishorganj', 'কিশোরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-427', 'Nilphamari Sadar', 'নীলফামারী সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-428', 'Sadullapur', 'সাদুল্লাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-429', 'Gaibandha Sadar', 'গাইবান্ধা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-430', 'Palashbari', 'পলাশবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-431', 'Saghata', 'সাঘাটা', 1, NULL, NULL, NOW(), NOW()),
('UPA-432', 'Gobindaganj', 'গোবিন্দগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-433', 'Sundarganj', 'সুন্দরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-434', 'Phulchari', 'ফুলছড়ি', 1, NULL, NULL, NOW(), NOW()),
('UPA-435', 'Thakurgaon Sadar', 'ঠাকুরগাঁও সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-436', 'Pirganj', 'পীরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-437', 'Ranisankail', 'রাণীশংকৈল', 1, NULL, NULL, NOW(), NOW()),
('UPA-438', 'Haripur', 'হরিপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-439', 'Baliadangi', 'বালিয়াডাঙ্গী', 1, NULL, NULL, NOW(), NOW()),
('UPA-440', 'Rangpur Sadar', 'রংপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-441', 'Gangachara', 'গংগাচড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-442', 'Taragonj', 'তারাগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-443', 'Badargonj', 'বদরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-444', 'Mithapukur', 'মিঠাপুকুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-445', 'Pirgonj', 'পীরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-446', 'Kaunia', 'কাউনিয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-447', 'Pirgacha', 'পীরগাছা', 1, NULL, NULL, NOW(), NOW()),
('UPA-448', 'Kurigram Sadar', 'কুড়িগ্রাম সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-449', 'Nageshwari', 'নাগেশ্বরী', 1, NULL, NULL, NOW(), NOW()),
('UPA-450', 'Bhurungamari', 'ভুরুঙ্গামারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-451', 'Phulbari', 'ফুলবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-452', 'Rajarhat', 'রাজারহাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-453', 'Ulipur', 'উলিপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-454', 'Chilmari', 'চিলমারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-455', 'Rowmari', 'রৌমারী', 1, NULL, NULL, NOW(), NOW()),
('UPA-456', 'Charrajibpur', 'চর রাজিবপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-457', 'Sherpur Sadar', 'শেরপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-458', 'Nalitabari', 'নালিতাবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-459', 'Sreebordi', 'শ্রীবরদী', 1, NULL, NULL, NOW(), NOW()),
('UPA-460', 'Nokla', 'নকলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-461', 'Jhenaigati', 'ঝিনাইগাতী', 1, NULL, NULL, NOW(), NOW()),
('UPA-462', 'Fulbaria', 'ফুলবাড়ীয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-463', 'Trishal', 'ত্রিশাল', 1, NULL, NULL, NOW(), NOW()),
('UPA-464', 'Bhaluka', 'ভালুকা', 1, NULL, NULL, NOW(), NOW()),
('UPA-465', 'Muktagacha', 'মুক্তাগাছা', 1, NULL, NULL, NOW(), NOW()),
('UPA-466', 'Mymensingh Sadar', 'ময়মনসিংহ সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-467', 'Dhobaura', 'ধোবাউড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-468', 'Phulpur', 'ফুলপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-469', 'Haluaghat', 'হালুয়াঘাট', 1, NULL, NULL, NOW(), NOW()),
('UPA-470', 'Gouripur', 'গৌরীপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-471', 'Gafargaon', 'গফরগাঁও', 1, NULL, NULL, NOW(), NOW()),
('UPA-472', 'Iswarganj', 'ঈশ্বরগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-473', 'Nandail', 'নান্দাইল', 1, NULL, NULL, NOW(), NOW()),
('UPA-474', 'Tarakanda', 'তারাকান্দা', 1, NULL, NULL, NOW(), NOW()),
('UPA-475', 'Jamalpur Sadar', 'জামালপুর সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-476', 'Melandah', 'মেলান্দহ', 1, NULL, NULL, NOW(), NOW()),
('UPA-477', 'Islampur', 'ইসলামপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-478', 'Dewangonj', 'দেওয়ানগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-479', 'Sarishabari', 'সরিষাবাড়ী', 1, NULL, NULL, NOW(), NOW()),
('UPA-480', 'Madarganj', 'মাদারগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-481', 'Bokshiganj', 'বকশীগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-482', 'Barhatta', 'বারহাট্টা', 1, NULL, NULL, NOW(), NOW()),
('UPA-483', 'Durgapur', 'দুর্গাপুর', 1, NULL, NULL, NOW(), NOW()),
('UPA-484', 'Kendua', 'কেন্দুয়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-485', 'Atpara', 'আটপাড়া', 1, NULL, NULL, NOW(), NOW()),
('UPA-486', 'Madan', 'মদন', 1, NULL, NULL, NOW(), NOW()),
('UPA-487', 'Khaliajuri', 'খালিয়াজুরী', 1, NULL, NULL, NOW(), NOW()),
('UPA-488', 'Kalmakanda', 'কলমাকান্দা', 1, NULL, NULL, NOW(), NOW()),
('UPA-489', 'Mohongonj', 'মোহনগঞ্জ', 1, NULL, NULL, NOW(), NOW()),
('UPA-490', 'Purbadhala', 'পূর্বধলা', 1, NULL, NULL, NOW(), NOW()),
('UPA-491', 'Netrokona Sadar', 'নেত্রকোণা সদর', 1, NULL, NULL, NOW(), NOW()),
('UPA-492', 'Eidgaon', 'ঈদগাঁও', 1, NULL, NULL, NOW(), NOW()),
('UPA-493', 'Madhyanagar', 'মধ্যনগর', 1, NULL, NULL, NOW(), NOW()),
('UPA-494', 'Dasar', 'ডাসার', 1, NULL, NULL, NOW(), NOW()),
('UPA-495', 'Shaistaganj', 'শায়েস্তাগঞ্জ', 1, NULL, NULL, NOW(), NOW());

-- Import BD Areas (4540 records)
-- Note: Areas may have complex parent references - using partial insert
INSERT INTO bd_areas (code, "nameEn", "nameBn", type, "upazilaId", "districtId", latitude, longitude, "createdAt", "updatedAt") VALUES
('ARE-1', 'Subil', 'সুবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-2', 'North Gunaighor', 'উত্তর গুনাইঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-3', 'South Gunaighor', 'দক্ষিণ গুনাইঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-4', 'Boroshalghor', 'বড়শালঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-5', 'Rajameher', 'রাজামেহার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-6', 'Yousufpur', 'ইউসুফপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-7', 'Rasulpur', 'রসুলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-8', 'Fatehabad', 'ফতেহাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-9', 'Elahabad', 'এলাহাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-10', 'Jafargonj', 'জাফরগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-11', 'Dhampti', 'ধামতী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-12', 'Mohanpur', 'মোহনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-13', 'Vani', 'ভানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-14', 'Barkamta', 'বরকামতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-15', 'Sultanpur', 'সুলতানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-16', 'Aganagar', 'আগানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-17', 'Bhabanipur', 'ভবানীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-18', 'North Khoshbas', 'উত্তর খোশবাস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-19', 'South Khoshbas', 'দক্ষিন খোশবাস', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-20', 'Jhalam', 'ঝলম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-21', 'Chitodda', 'চিতড্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-22', 'North Shilmuri', 'উত্তর শিলমুড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-23', 'South Shilmuri', 'দক্ষিন শিলমুড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-24', 'Galimpur', 'গালিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-25', 'Shakpur', 'শাকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-26', 'Bhaukshar', 'ভাউকসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-27', 'Adda', 'আড্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-28', 'Adra', 'আদ্রা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-29', 'Payalgacha', 'পয়ালগাছা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-30', 'Laxmipur', 'লক্ষীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-31', 'Shidli', 'শিদলাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-32', 'Chandla', 'চান্দলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-33', 'Shashidal', 'শশীদল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-34', 'Dulalpur', 'দুলালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-35', 'Brahmanpara Sadar', 'ব্রাহ্মনপাড়া সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-36', 'Shahebabad', 'সাহেবাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-37', 'Malapara', 'মালাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-38', 'Madhabpur', 'মাধবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-39', 'Shuhilpur', 'সুহিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-40', 'Bataghashi', 'বাতাঘাসি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-41', 'Joag', 'জোয়াগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-42', 'Borcarai', 'বরকরই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-43', 'Madhaiya', 'মাধাইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-44', 'Dollai Nowabpur', 'দোল্লাই নবাবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-45', 'Mohichial', 'মহিচাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-46', 'Gollai', 'গল্লাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-47', 'Keronkhal', 'কেরণখাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-48', 'Maijkhar', 'মাইজখার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-49', 'Etberpur', 'এতবারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-50', 'Barera', 'বাড়েরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-51', 'Borcoit', 'বরকইট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-52', 'Sreepur', 'শ্রীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-53', 'Kashinagar', 'কাশিনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-54', 'Kalikapur', 'কালিকাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-55', 'Shuvapur', 'শুভপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-56', 'Ghulpasha', 'ঘোলপাশা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-57', 'Moonshirhat', 'মুন্সীরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-58', 'Batisha', 'বাতিসা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-59', 'Kankapait', 'কনকাপৈত', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-60', 'Cheora', 'চিওড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-61', 'Jagannatdighi', 'জগন্নাথদিঘী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-62', 'Goonabati', 'গুনবতী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-63', 'Alkara', 'আলকরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-64', 'Doulotpur', 'দৌলতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-65', 'Daudkandi', 'দাউদকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-66', 'North Eliotgonj', 'উত্তর ইলিয়টগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-67', 'South Eliotgonj', 'দক্ষিন ইলিয়টগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-68', 'Zinglatoli', 'জিংলাতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-69', 'Sundolpur', 'সুন্দলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-70', 'Gouripur', 'গৌরীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-71', 'East Mohammadpur', 'পুর্ব মোহাম্মদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-72', 'West Mohammadpur', 'পশ্চিম মোহাম্মদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-73', 'Goalmari', 'গোয়ালমারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-74', 'Maruka', 'মারুকা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-75', 'Betessor', 'বিটেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-76', 'Podua', 'পদুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-77', 'West Passgacia', 'পশ্চিম পাচঁগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-78', 'Baropara', 'বারপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-79', 'Mathabanga', 'মাথাভাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-80', 'Gagutiea', 'ঘাগুটিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-81', 'Asadpur', 'আছাদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-82', 'Chanderchor', 'চান্দেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-83', 'Vashania', 'ভাষানিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-84', 'Nilokhi', 'নিলখী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-85', 'Garmora', 'ঘারমোড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-86', 'Joypur', 'জয়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-87', 'Dulalpur', 'দুলালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-88', 'Bakoi', 'বাকই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-89', 'Mudafargonj', 'মুদাফফর গঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-90', 'Kandirpar', 'কান্দিরপাড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-91', 'Gobindapur', 'গোবিন্দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-92', 'Uttarda', 'উত্তরদা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-93', 'Laksam Purba', 'লাকসাম পুর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-94', 'Azgora', 'আজগরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-95', 'Sreekil', 'শ্রীকাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-96', 'Akubpur', 'আকুবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-97', 'Andicot', 'আন্দিকোট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-98', 'Purbadair (East)', 'পুর্বধৈইর (পুর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-99', 'Purbadair (West)', 'পুর্বধৈইর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-100', 'Bangara (East)', 'বাঙ্গরা (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-101', 'Bangara (West)', 'বাঙ্গরা (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-102', 'Chapitala', 'চাপিতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-103', 'Camalla', 'কামাল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-104', 'Jatrapur', 'যাত্রাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-105', 'Ramachandrapur (North)', 'রামচন্দ্রপুর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-106', 'Ramachandrapur (South)', 'রামচন্দ্রপুর (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-107', 'Muradnagar Sadar', 'মুরাদনগর সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-108', 'Nobipur (East)', 'নবীপুর (পুর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-109', 'Nobipur (West)', 'নবীপুর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-110', 'Damgar', 'ধামঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-111', 'Jahapur', 'জাহাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-112', 'Salikandi', 'ছালিয়াকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-113', 'Darura', 'দারোরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-114', 'Paharpur', 'পাহাড়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-115', 'Babutipara', 'বাবুটিপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-116', 'Tanki', 'টনকী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-117', 'Bangadda', 'বাঙ্গড্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-118', 'Paria', 'পেরিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-119', 'Raykot', 'রায়কোট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-120', 'Mokara', 'মোকরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-121', 'Makrabpur', 'মক্রবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-122', 'Heshakhal', 'হেসাখাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-123', 'Adra', 'আদ্রা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-124', 'Judda', 'জোড্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-125', 'Dhalua', 'ঢালুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-126', 'Doulkha', 'দৌলখাঁড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-127', 'Boxgonj', 'বক্সগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-128', 'Satbaria', 'সাতবাড়ীয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-129', 'Kalirbazer', 'কালীর বাজার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-130', 'North Durgapur', 'উত্তর দুর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-131', 'South Durgapur', 'দক্ষিন দুর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-132', 'Amratoli', 'আমড়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-133', 'Panchthubi', 'পাঁচথুবী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-134', 'Jagannatpur', 'জগন্নাথপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-135', 'Chandanpur', 'চন্দনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-136', 'Chalibanga', 'চালিভাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-137', 'Radanagar', 'রাধানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-138', 'Manikarchar', 'মানিকারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-139', 'Barakanda', 'বড়কান্দা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-140', 'Govindapur', 'গোবিন্দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-141', 'Luterchar', 'লুটেরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-142', 'Vaorkhola', 'ভাওরখোলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-143', 'Baishgaon', 'বাইশগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-144', 'Shoroshpur', 'সরসপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-145', 'Hasnabad', 'হাসনাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-146', 'Jholam (North)', 'ঝলম (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-147', 'Jholam (South)', 'ঝলম (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-148', 'Moishatua', 'মৈশাতুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-149', 'Lokkhanpur', 'লক্ষনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-150', 'Khela', 'খিলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-151', 'Uttarhowla', 'উত্তর হাওলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-152', 'Natherpetua', 'নাথেরপেটুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-153', 'Bipulashar', 'বিপুলাসার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-154', 'Chuwara', 'চৌয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-155', 'Baropara', 'বারপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-156', 'Jorkanoneast', 'জোড়কানন (পুর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-157', 'Goliara', 'গলিয়ারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-158', 'Jorkanonwest', 'জোড়কানন (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-159', 'Bagmara (North)', 'বাগমারা (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-160', 'Bagmara (South)', 'বাগমারা (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-161', 'Bhuloin (North)', 'ভূলইন (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-162', 'Bhuloin (South)', 'ভূলইন (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-163', 'Belgor (North)', 'বেলঘর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-164', 'Belgor (South)', 'বেলঘর (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-165', 'Perul (North)', 'পেরুল (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-166', 'Perul (South)', 'পেরুল (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-167', 'Bijoypur', 'বিজয়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-168', 'Satani', 'সাতানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-169', 'Jagatpur', 'জগতপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-170', 'Balorampur', 'বলরামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-171', 'Karikandi', 'কড়িকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-172', 'Kalakandi', 'কলাকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-173', 'Vitikandi', 'ভিটিকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-174', 'Narayandia', 'নারান্দিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-175', 'Zearkandi', 'জিয়ারকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-176', 'Majidpur', 'মজিদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-177', 'Moynamoti', 'ময়নামতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-178', 'Varella', 'ভারেল্লা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-179', 'Mokam', 'মোকাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-180', 'Burichang Sadar', 'বুড়িচং সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-181', 'Bakshimul', 'বাকশীমূল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-182', 'Pirjatrapur', 'পীরযাত্রাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-183', 'Sholonal', 'ষোলনল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-184', 'Rajapur', 'রাজাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-185', 'Bagmara (North)', 'বাগমারা (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-186', 'Bagmara (South)', 'বাগমারা (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-187', 'Bhuloin (North)', 'ভূলইন (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-188', 'Bhuloin (South)', 'ভূলইন (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-189', 'Belgor (North)', 'বেলঘর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-190', 'Belgor (South)', 'বেলঘর (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-191', 'Perul (North)', 'পেরুল (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-192', 'Perul (South)', 'পেরুল (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-193', 'Mohamaya', 'মহামায়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-194', 'Pathannagar', 'পাঠাননগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-195', 'Subhapur', 'শুভপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-196', 'Radhanagar', 'রাধানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-197', 'Gopal', 'ঘোপাল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-198', 'Sarishadi', 'শর্শদি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-199', 'Panchgachia', 'পাঁচগাছিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-200', 'Dhormapur', 'ধর্মপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-201', 'Kazirbag', 'কাজিরবাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-202', 'Kalidah', 'কালিদহ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-203', 'Baligaon', 'বালিগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-204', 'Dholia', 'ধলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-205', 'Lemua', 'লেমুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-206', 'Chonua', 'ছনুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-207', 'Motobi', 'মোটবী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-208', 'Fazilpur', 'ফাজিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-209', 'Forhadnogor', 'ফরহাদনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-210', 'Charmozlishpur', 'চরমজলিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-211', 'Bogadana', 'বগাদানা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-212', 'Motigonj', 'মতিগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-213', 'Mongolkandi', 'মঙ্গলকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-214', 'Chardorbesh', 'চরদরবেশ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-215', 'Chorchandia', 'চরচান্দিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-216', 'Sonagazi', 'সোনাগাজী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-217', 'Amirabad', 'আমিরাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-218', 'Nababpur', 'নবাবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-219', 'Fulgazi', 'ফুলগাজী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-220', 'Munshirhat', 'মুন্সিরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-221', 'Dorbarpur', 'দরবারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-222', 'Anandopur', 'আনন্দপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-223', 'Amzadhat', 'আমজাদহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-224', 'Gmhat', 'জি,এম, হাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-225', 'Mizanagar', 'মির্জানগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-226', 'Ctholia', 'চিথলিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-227', 'Boxmahmmud', 'বক্সমাহমুদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-228', 'Sindurpur', 'সিন্দুরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-229', 'Rajapur', 'রাজাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-230', 'Purbachandrapur', 'পূর্বচন্দ্রপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-231', 'Ramnagar', 'রামনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-232', 'Yeakubpur', 'ইয়াকুবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-233', 'Daganbhuiyan', 'দাগনভূঞা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-234', 'Matubhuiyan', 'মাতুভূঞা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-235', 'Jayloskor', 'জায়লস্কর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-236', 'Basudeb', 'বাসুদেব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-237', 'Machihata', 'মাছিহাতা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-238', 'Sultanpur', 'সুলতানপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-239', 'Ramrail', 'রামরাইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-240', 'Sadekpur', 'সাদেকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-241', 'Talsahar', 'তালশহর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-242', 'Natai', 'নাটাই (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-243', 'Natai', 'নাটাই (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-244', 'Shuhilpur', 'সুহিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-245', 'Bodhal', 'বুধল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-246', 'Majlishpur', 'মজলিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-247', 'Mulagram', 'মূলগ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-248', 'Mehari', 'মেহারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-249', 'Badair', 'বাদৈর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-250', 'Kharera', 'খাড়েরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-251', 'Benauty', 'বিনাউটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-252', 'Gopinathpur', 'গোপীনাথপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-253', 'Kasbaw', 'কসবা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-254', 'Kuti', 'কুটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-255', 'Kayempur', 'কাইমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-256', 'Bayek', 'বায়েক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-257', 'Chatalpar', 'চাতলপাড়', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-258', 'Bhalakut', 'ভলাকুট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-259', 'Kunda', 'কুন্ডা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-260', 'Goalnagar', 'গোয়ালনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-261', 'Nasirnagar', 'নাসিরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-262', 'Burishwar', 'বুড়িশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-263', 'Fandauk', 'ফান্দাউক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-264', 'Goniauk', 'গুনিয়াউক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-265', 'Chapartala', 'চাপৈরতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-266', 'Dharnondol', 'ধরমন্ডল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-267', 'Haripur', 'হরিপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-268', 'Purbabhag', 'পূর্বভাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-269', 'Gokarna', 'গোকর্ণ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-270', 'Auraol', 'অরুয়াইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-271', 'Pakshimuul', 'পাকশিমুল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-272', 'Chunta', 'চুন্টা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-273', 'Kalikaccha', 'কালীকচ্ছ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-274', 'Panishor', 'পানিশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-275', 'Sarail', 'সরাইল সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-276', 'Noagoun', 'নোয়াগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-277', 'Shahajadapur', 'শাহজাদাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-278', 'Shahbazpur', 'শাহবাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-279', 'Ashuganj', 'আশুগঞ্জ সদর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-280', 'Charchartala', 'চরচারতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-281', 'Durgapur', 'দুর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-282', 'Araishidha', 'আড়াইসিধা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-283', 'Talshaharw', 'তালশহর(পঃ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-284', 'Sarifpur', 'শরীফপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-285', 'Lalpur', 'লালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-286', 'Tarua', 'তারুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-287', 'Monionda', 'মনিয়ন্দ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-288', 'Dharkhar', 'ধরখার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-289', 'Mogra', 'মোগড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-290', 'Akhauran', 'আখাউড়া (উঃ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-291', 'Akhauras', 'আখাউড়া (দঃ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-292', 'Barail', 'বড়াইল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-293', 'Birgaon', 'বীরগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-294', 'Krishnanagar', 'কৃষ্ণনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-295', 'Nathghar', 'নাটঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-296', 'Biddayakut', 'বিদ্যাকুট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-297', 'Nabinagare', 'নবীনগর (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-298', 'Nabinagarw', 'নবীনগর(পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-299', 'Bitghar', 'বিটঘর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-300', 'Shibpur', 'শিবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-301', 'Sreerampur', 'শ্রীরামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-302', 'Jinudpur', 'জিনোদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-303', 'Laurfatehpur', 'লাউরফতেপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-304', 'Ibrahimpur', 'ইব্রাহিমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-305', 'Satmura', 'সাতমোড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-306', 'Shamogram', 'শ্যামগ্রাম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-307', 'Rasullabad', 'রসুল্লাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-308', 'Barikandi', 'বড়িকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-309', 'Salimganj', 'ছলিমগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-310', 'Ratanpur', 'রতনপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-311', 'Kaitala (North)', 'কাইতলা (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-312', 'Kaitala (South)', 'কাইতলা (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-313', 'Tazkhali', 'তেজখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-314', 'Pahariya Kandi', 'পাহাড়িয়া কান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-315', 'Dariadulat', 'দরিয়াদৌলত', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-316', 'Sonarampur', 'সোনারামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-317', 'Darikandi', 'দড়িকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-318', 'Saifullyakandi', 'ছয়ফুল্লাকান্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-319', 'Bancharampur', 'বাঞ্ছারামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-320', 'Ayabpur', 'আইয়ুবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-321', 'Fardabad', 'ফরদাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-322', 'Rupushdi', 'রুপসদী পশ্চিম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-323', 'Salimabad', 'ছলিমাবাদ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-324', 'Ujanchar', 'উজানচর পূর্ব', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-325', 'Manikpur', 'মানিকপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-326', 'Bhudanty', 'বুধন্তি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-327', 'Chandura', 'চান্দুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-328', 'Ichapura', 'ইছাপুরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-329', 'Champaknagar', 'চম্পকনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-330', 'Harashpur', 'হরষপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-331', 'Pattan', 'পত্তন', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-332', 'Singerbil', 'সিংগারবিল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-333', 'Bishupor', 'বিষ্ণুপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-334', 'Charislampur', 'চর-ইসলামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-335', 'Paharpur', 'পাহাড়পুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-336', 'Jibtali', 'জীবতলি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-337', 'Sapchari', 'সাপছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-338', 'Kutukchari', 'কুতুকছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-339', 'Bandukbhanga', 'বন্দুকভাঙ্গা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-340', 'Balukhali', 'বালুখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-341', 'Mogban', 'মগবান', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-342', 'Raikhali', 'রাইখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-343', 'Kaptai', 'কাপ্তাই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-344', 'Wagga', 'ওয়াজ্ঞা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-345', 'Chandraghona', 'চন্দ্রঘোনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-346', 'Chitmorom', 'চিৎমরম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-347', 'Ghagra', 'ঘাগড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-348', 'Fatikchari', 'ফটিকছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-349', 'Betbunia', 'বেতবুনিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-350', 'Kalampati', 'কলমপতি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-351', 'Sajek', 'সাজেক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-352', 'Amtali', 'আমতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-353', 'Bongoltali', 'বঙ্গলতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-354', 'Rupokari', 'রুপকারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-355', 'Marisha', 'মারিশ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-356', 'Khedarmara', 'খেদারমারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-357', 'Sharoyatali', 'সারোয়াতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-358', 'Baghaichari', 'বাঘাইছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-359', 'Subalong', 'সুবলং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-360', 'Barkal', 'বরকল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-361', 'Bushanchara', 'ভূষনছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-362', 'Aimachara', 'আইমাছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-363', 'Borohorina', 'বড় হরিণা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-364', 'Langad', 'লংগদু', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-365', 'Maeinimukh', 'মাইনীমুখ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-366', 'Vasannadam', 'ভাসান্যাদম', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-367', 'Bogachattar', 'বগাচতর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-368', 'Gulshakhali', 'গুলশাখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-369', 'Kalapakujja', 'কালাপাকুজ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-370', 'Atarakchara', 'আটারকছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-371', 'Ghilachari', 'ঘিলাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-372', 'Gaindya', 'গাইন্দ্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-373', 'Bangalhalia', 'বাঙ্গালহালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-374', 'Kengrachari', 'কেংড়াছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-375', 'Belaichari', 'বিলাইছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-376', 'Farua', 'ফারুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-377', 'Juraichari', 'জুরাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-378', 'Banajogichara', 'বনযোগীছড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-379', 'Moidong', 'মৈদং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-380', 'Dumdumya', 'দুমদুম্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-381', 'Sabekkhong', 'সাবেক্ষ্যং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-382', 'Naniarchar', 'নানিয়ারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-383', 'Burighat', 'বুড়িঘাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-384', 'Ghilachhari', 'ঘিলাছড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-385', 'Charmatua', 'চরমটুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-386', 'Dadpur', 'দাদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-387', 'Noannoi', 'নোয়ান্নই', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-388', 'Kadirhanif', 'কাদির হানিফ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-389', 'Binodpur', 'বিনোদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-390', 'Dharmapur', 'ধর্মপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-391', 'Aujbalia', 'এওজবালিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-392', 'Kaladara', 'কালাদরপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-393', 'Ashwadia', 'অশ্বদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-394', 'Newajpur', 'নিয়াজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-395', 'East Charmatua', 'পূর্ব চরমটুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-396', 'Andarchar', 'আন্ডারচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-397', 'Noakhali', 'নোয়াখালী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-398', 'Sirajpur', 'সিরাজপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-399', 'Charparboti', 'চরপার্বতী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-400', 'Charhazari', 'চরহাজারী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-401', 'Charkakra', 'চরকাঁকড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-402', 'Charfakira', 'চরফকিরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-403', 'Musapur', 'মুসাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-404', 'Charelahi', 'চরএলাহী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-405', 'Rampur', 'রামপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-406', 'Amanullapur', 'আমানউল্ল্যাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-407', 'Gopalpur', 'গোপালপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-408', 'Jirtali', 'জিরতলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-409', 'Kutubpur', 'কুতবপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-410', 'Alyearpur', 'আলাইয়ারপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-411', 'Chayani', 'ছয়ানী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-412', 'Rajganj', 'রাজগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-413', 'Eklashpur', 'একলাশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-414', 'Begumganj', 'বেগমগঞ্জ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-415', 'Mirwarishpur', 'মিরওয়ারিশপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-416', 'Narottampur', 'নরোত্তমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-417', 'Durgapur', 'দূর্গাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-418', 'Rasulpur', 'রসুলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-419', 'Hajipur', 'হাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-420', 'Sharifpur', 'শরীফপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-421', 'Kadirpur', 'কাদিরপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-422', 'Sukhchar', 'সুখচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-423', 'Nolchira', 'নলচিরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-424', 'Charishwar', 'চরঈশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-425', 'Charking', 'চরকিং', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-426', 'Tomoroddi', 'তমরদ্দি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-427', 'Sonadiya', 'সোনাদিয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-428', 'Burirchar', 'বুড়িরচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-429', 'Jahajmara', 'জাহাজমারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-430', 'Nijhumdwi', 'নিঝুমদ্বীপ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-431', 'Charjabbar', 'চরজাব্বার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-432', 'Charbata', 'চরবাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-433', 'Charclerk', 'চরক্লার্ক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-434', 'Charwapda', 'চরওয়াপদা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-435', 'Charjubilee', 'চরজুবলী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-436', 'Charaman Ullah', 'চরআমান উল্যা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-437', 'East Charbata', 'পূর্ব চরবাটা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-438', 'Mohammadpur', 'মোহাম্মদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-439', 'Narottampur', 'নরোত্তমপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-440', 'Dhanshiri', 'ধানসিঁড়ি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-441', 'Sundalpur', 'সুন্দলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-442', 'Ghoshbag', 'ঘোষবাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-443', 'Chaprashirhat', 'চাপরাশিরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-444', 'Dhanshalik', 'ধানশালিক', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-445', 'Batoiya', 'বাটইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-446', 'Chhatarpaia', 'ছাতারপাইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-447', 'Kesharpar', 'কেশরপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-448', 'Dumurua', 'ডুমুরুয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-449', 'Kadra', 'কাদরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-450', 'Arjuntala', 'অর্জুনতলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-451', 'Kabilpur', 'কাবিলপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-452', 'Mohammadpur', 'মোহাম্মদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-453', 'Nabipur', 'নবীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-454', 'Bejbagh', 'বিজবাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-455', 'Sahapur', 'সাহাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-456', 'Ramnarayanpur', 'রামনারায়নপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-457', 'Porokote', 'পরকোট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-458', 'Badalkot', 'বাদলকোট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-459', 'Panchgaon', 'পাঁচগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-460', 'Hat-Pukuria Ghatlabag', 'হাট-পুকুরিয়া ঘাটলাবাগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-461', 'Noakhala', 'নোয়াখলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-462', 'Khilpara', 'খিলপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-463', 'Mohammadpur', 'মোহাম্মদপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-464', 'Joyag', 'জয়াগ', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-465', 'Nodona', 'নদনা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-466', 'Chashirhat', 'চাষীরহাট', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-467', 'Barogaon', 'বারগাঁও', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-468', 'Ambarnagor', 'অম্বরনগর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-469', 'Nateshwar', 'নাটেশ্বর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-470', 'Bajra', 'বজরা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-471', 'Sonapur', 'সোনাপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-472', 'Deoti', 'দেওটি', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-473', 'Amishapara', 'আমিশাপাড়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-474', 'Gazipur', 'গাজীপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-475', 'Algidurgapur (North)', 'আলগী দুর্গাপুর (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-476', 'Algidurgapur (South)', 'আলগী দুর্গাপুর (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-477', 'Nilkamal', 'নীলকমল', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-478', 'Haimchar', 'হাইমচর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-479', 'Charbhairabi', 'চরভৈরবী', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-480', 'Pathair', 'পাথৈর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-481', 'Bitara', 'বিতারা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-482', 'Shohodebpur (East)', 'সহদেবপুর (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-483', 'Shohodebpur (West)', 'সহদেবপুর (পশ্চিম)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-484', 'Kachua (North)', 'কচুয়া (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-485', 'Kachua (South)', 'কচুয়া (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-486', 'Gohat (North)', 'গোহাট (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-487', 'Kadla', 'কাদলা', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-488', 'Ashrafpur', 'আসরাফপুর', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-489', 'Gohat (South)', 'গোহাট (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-490', 'Sachar', 'সাচার', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-491', 'Koroia', 'কড়ইয়া', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-492', 'Tamta (South)', 'টামটা (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-493', 'Tamta (North)', 'টামটা (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-494', 'Meher (North)', 'মেহের (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-495', 'Meher (South)', 'মেহের (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-496', 'Suchipara (North)', 'সুচিপাড়া (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-497', 'Suchipara (South)', 'সুচিপাড়া (দক্ষিণ)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-498', 'Chitoshi (East)', 'চিতষী (পূর্ব)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-499', 'Raysree (South)', 'রায়শ্রী (দক্ষিন)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW()),
('ARE-500', 'Raysree (North)', 'রায়শ্রী (উত্তর)', 'UNION', NULL, NULL, NULL, NULL, NOW(), NOW());

-- Note: 4040 additional areas deferred due to SQL size limits
-- These will be imported in a separate batch
